; wEventFlags bit flags

	const_def
; The first eight flags are reset upon reloading the map
	const EVENT_TEMPORARY_UNTIL_MAP_RELOAD_1
	const EVENT_TEMPORARY_UNTIL_MAP_RELOAD_2
	const EVENT_TEMPORARY_UNTIL_MAP_RELOAD_3
	const EVENT_TEMPORARY_UNTIL_MAP_RELOAD_4
	const EVENT_TEMPORARY_UNTIL_MAP_RELOAD_5
	const EVENT_TEMPORARY_UNTIL_MAP_RELOAD_6
	const EVENT_TEMPORARY_UNTIL_MAP_RELOAD_7
	const EVENT_TEMPORARY_UNTIL_MAP_RELOAD_8
; Johto Gym Leader TM gifts
	const EVENT_GOT_TM31_MUD_SLAP
	const EVENT_GOT_TM49_FURY_CUTTER
	const EVENT_GOT_TM01_METEOR_MASH
	const EVENT_GOT_TM45_ATTRACT
	const EVENT_GOT_TM30_SHADOW_BALL
	const EVENT_GOT_TM23_IRON_TAIL
	const EVENT_GOT_TM16_ICY_WIND
	const EVENT_GOT_TM24_DRAGONBREATH
; HMs items (EVENT_GOT_MILOTIC_CALL is with the Johto itemballs)
	const EVENT_GOT_MAREEP_CALL
	const EVENT_GOT_HM01_FLY
	const EVENT_GOT_SCYTHER_CALL
	const EVENT_GOT_LANTURN_CALL
	const EVENT_GOT_DONPHAN_CALL
	const EVENT_GOT_KINGDRA_CALL
	const EVENT_CAUGHT_ALL_UNOWN
; Rods
	const EVENT_GOT_OLD_ROD
	const EVENT_GOT_GOOD_ROD
; Johto story events
	const EVENT_GOT_A_POKEMON_FROM_ELM
	const EVENT_GOT_CYNDAQUIL_FROM_ELM
	const EVENT_GOT_TOTODILE_FROM_ELM
	const EVENT_GOT_CHIKORITA_FROM_ELM
	const EVENT_CHERRYGROVE_SACRED_ASH
	const EVENT_EARLS_ACADEMY_LUCKY_EGG
	const_skip
	const EVENT_JASMINE_RETURNED_TO_GYM
	const EVENT_CLEARED_RADIO_TOWER
	const EVENT_CLEARED_ROCKET_HIDEOUT
	const EVENT_GOT_SECRETPOTION_FROM_PHARMACY
	const EVENT_ELMS_TRAVEL_NOTEBOOK
	const EVENT_USED_THE_CARD_KEY_IN_THE_RADIO_TOWER
	const EVENT_REFUSED_TO_HELP_LANCE_AT_LAKE_OF_RAGE
	const EVENT_GOT_BERRY_FROM_ROUTE_2_HOUSE
	const EVENT_MADE_WHITNEY_CRY
	const EVENT_HERDED_SCYTHER
	const EVENT_FOUGHT_SUDOWOODO
	const_skip
	const_skip
	const_skip
	const EVENT_MADE_UNOWN_APPEAR_IN_RUINS
	const EVENT_MET_NURSE_JOY
	const EVENT_SHINY_CHARM_OBTAINED
	const EVENT_OAKSLAB_NAYRU62
	const EVENT_GOT_WIDE_LENS
	const MET_NUGGET_SELLER
	const EVENT_SHINY_MON_CODEX
	const EVENT_KURT_GAVE_YOU_LURE_BALL
	const EVENT_INITIALIZED_EVENTS
	const EVENT_JASMINE_EXPLAINED_AMPHYS_SICKNESS
	const EVENT_LAKE_OF_RAGE_EXPLAINED_WEIRD_MAGIKARP
	const EVENT_LAKE_OF_RAGE_ASKED_FOR_MAGIKARP
	const EVENT_LAKE_OF_RAGE_ELIXIR_ON_STANDBY
	const EVENT_CELEBI_FATEFUL_ENCOUNTER
	const EVENT_ECRUTEAK_BLACKSMITH_FINDS_HIS_PASSION
	const EVENT_HEALED_MOOMOO
	const EVENT_GOT_TM13_SNORE_FROM_MOOMOO_FARM
	const EVENT_TALKED_TO_FARMER_ABOUT_MOOMOO
	const EVENT_POKEMON_LEAGUE_CHAMPION

	const EVENT_BEAT_ELITE_FOUR
	const EVENT_GOT_SHUCKIE
	const EVENT_MANIA_TOOK_SHUCKIE_OR_LET_YOU_KEEP_HIM
	const EVENT_GOT_SUNNY_DAY_FROM_RADIO_TOWER
	const EVENT_GOT_PINK_BOW_FROM_MARY
	const EVENT_USED_BASEMENT_KEY
	const EVENT_RECEIVED_CARD_KEY
	const EVENT_GOT_TM_BRICK_BREAK
	const EVENT_LANCE_HEALED_YOU_IN_TEAM_ROCKET_BASE
	const EVENT_GOT_MYSTIC_WATER_IN_CHERRYGROVE
	const EVENT_GOT_TM05_ROAR
	const EVENT_GOT_EEVEE
	const EVENT_GOT_KENYA
	const EVENT_GAVE_KENYA
	const EVENT_GOT_HP_UP_FROM_RANDY
	const EVENT_GOT_TM_AURA_SPHERE
	const EVENT_ILEX_FOREST_HIDDEN_LEAF_STONE
	const EVENT_ILEX_FOREST_HIDDEN_SUN_STONE
	const EVENT_ILEX_FOREST_HIDDEN_SILVER_LEAF
	const EVENT_ILEX_FOREST_HIDDEN_GOLD_LEAF
	const EVENT_ILEX_FOREST_HIDDEN_GOLD_BERRY
	const_skip
	const EVENT_GOT_QUICK_CLAW
	const EVENT_MET_HIDDEN_POWER_GUY
	const EVENT_GOT_TM36_SLUDGE_BOMB
	const EVENT_GOT_ITEMFINDER
	const EVENT_GOT_BICYCLE
	const EVENT_GOT_SQUIRTBOTTLE
	const EVENT_GOT_MIRACLE_SEED_IN_ROUTE_4
	const EVENT_GOT_CHARCOAL_IN_CHARCOAL_KILN
	const EVENT_GOT_TM_HEADBUTT
	const EVENT_DECIDED_TO_HELP_LANCE
	const EVENT_GOT_TYROGUE_FROM_KIYO
	const EVENT_MET_FRIEDA_OF_FRIDAY
	const EVENT_GOT_POISON_BARB_FROM_FRIEDA
	const EVENT_MET_TUSCANY_OF_TUESDAY
	const EVENT_GOT_PINK_BOW_FROM_TUSCANY
	const EVENT_MET_ARTHUR_OF_THURSDAY
	const EVENT_GOT_HARD_STONE_FROM_ARTHUR
	const EVENT_MET_SUNNY_OF_SUNDAY
	const EVENT_GOT_MAGNET_FROM_SUNNY
	const EVENT_MET_WESLEY_OF_WEDNESDAY
	const EVENT_GOT_BLACKBELT_FROM_WESLEY
	const EVENT_MET_SANTOS_OF_SATURDAY
	const EVENT_GOT_SPELL_TAG_FROM_SANTOS
	const EVENT_MET_MONICA_OF_MONDAY
	const EVENT_GOT_SHARP_BEAK_FROM_MONICA
	const EVENT_GOT_LEFTOVERS_FROM_KATE
	const EVENT_GOT_FIRST_SHINY_BALL_FOR_FREE
	const EVENT_GOT_BLACKGLASSES_IN_DARK_CAVE
	const EVENT_GOT_KINGS_ROCK_IN_SLOWPOKE_WELL
	const EVENT_I_WANT_TO_DO_SOMETHING
	const EVENT_GOT_TM37_SANDSTORM
	const EVENT_FIRST_TIME_BANKING_WITH_MOM
	const_skip
	const EVENT_GOT_CLEAR_BELL
	const EVENT_ROUTE_7_OTIS
	const EVENT_GOT_TANGELA_CALL
	const EVENT_RELEASED_THE_BEASTS
	const EVENT_GOT_MASTER_BALL_FROM_ELM
; Johto hidden items
	const EVENT_TIN_TOWER_4F_HIDDEN_MAX_POTION
	const EVENT_TIN_TOWER_5F_HIDDEN_FULL_RESTORE
	const EVENT_TIN_TOWER_5F_HIDDEN_CARBOS
	const EVENT_BURNED_TOWER_1F_HIDDEN_ETHER
	const EVENT_GAVE_SCIENTIST_OLD_AMBER
	const EVENT_GAVE_SCIENTIST_ROOT_FOSSIL
	const EVENT_GAVE_SCIENTIST_HELIX_FOSSIL
	const EVENT_NATIONAL_PARK_HIDDEN_FULL_HEAL
	const EVENT_OLIVINE_LIGHTHOUSE_5F_HIDDEN_HYPER_POTION
	const EVENT_TEAM_ROCKET_BASE_B1F_HIDDEN_REVIVE
	const EVENT_TEAM_ROCKET_BASE_B2F_HIDDEN_FULL_HEAL
	const EVENT_ILEX_FOREST_HIDDEN_MAX_ETHER
	const EVENT_ILEX_FOREST_HIDDEN_HYPER_POTION
	const EVENT_ILEX_FOREST_HIDDEN_FULL_HEAL
	const EVENT_GOLDENROD_UNDERGROUND_HIDDEN_PARLYZ_HEAL
	const EVENT_GOLDENROD_UNDERGROUND_HIDDEN_SUPER_POTION
	const EVENT_GOLDENROD_UNDERGROUND_HIDDEN_ANTIDOTE
	const EVENT_GOLDENROD_UNDERGROUND_SWITCH_ROOM_ENTRANCES_HIDDEN_MAX_POTION
	const EVENT_GOLDENROD_UNDERGROUND_SWITCH_ROOM_ENTRANCES_HIDDEN_REVIVE
	const EVENT_MOUNT_MORTAR_1F_OUTSIDE_HIDDEN_HYPER_POTION
	const EVENT_MOUNT_MORTAR_1F_INSIDE_HIDDEN_MAX_REPEL
	const EVENT_MOUNT_MORTAR_2F_INSIDE_HIDDEN_FULL_RESTORE
	const EVENT_MOUNT_MORTAR_B1F_HIDDEN_MAX_REVIVE
	const EVENT_ICE_PATH_B1F_HIDDEN_MAX_POTION
	const EVENT_ICE_PATH_B2F_MAHOGANY_SIDE_HIDDEN_CARBOS
	const EVENT_ICE_PATH_B2F_BLACKTHORN_SIDE_HIDDEN_ICE_HEAL
	const EVENT_WHIRL_ISLAND_B1F_HIDDEN_RARE_CANDY
	const EVENT_WHIRL_ISLAND_B1F_HIDDEN_ULTRA_BALL
	const EVENT_WHIRL_ISLAND_B1F_HIDDEN_FULL_RESTORE
	const EVENT_SILVER_CAVE_ROOM_1_HIDDEN_DIRE_HIT
	const EVENT_SILVER_CAVE_ROOM_1_HIDDEN_ULTRA_BALL
	const EVENT_SILVER_CAVE_ROOM_2_HIDDEN_MAX_POTION
	const EVENT_DARK_CAVE_VIOLET_ENTRANCE_HIDDEN_ELIXER
	const EVENT_VICTORY_ROAD_HIDDEN_MAX_POTION
	const EVENT_VICTORY_ROAD_HIDDEN_FULL_HEAL
	const EVENT_DRAGONS_DEN_B1F_HIDDEN_REVIVE
	const EVENT_DRAGONS_DEN_B1F_HIDDEN_MAX_POTION
	const EVENT_DRAGONS_DEN_B1F_HIDDEN_MAX_ELIXER
	const EVENT_ROUTE_13_OTIS
	const EVENT_ROUTE_2_HIDDEN_POTION
	const EVENT_ROUTE_4_HIDDEN_GREAT_BALL
	const EVENT_ROUTE_4_HIDDEN_SUPER_POTION
	const EVENT_ROUTE_6_HIDDEN_RARE_CANDY
	const EVENT_ROUTE_6_HIDDEN_HYPER_POTION
	const EVENT_ROUTE_9_HIDDEN_ETHER
	const EVENT_ROUTE_11_HIDDEN_NUGGET
	const EVENT_ROUTE_12_HIDDEN_HYPER_POTION
	const EVENT_ROUTE_13_HIDDEN_MAX_ETHER
	const EVENT_ROUTE_14_HIDDEN_MAX_POTION
	const EVENT_ROUTE_16_HIDDEN_ELIXER
	const EVENT_ROUTE_17_HIDDEN_PP_UP
	const EVENT_VIOLET_CITY_HIDDEN_HYPER_POTION
	const EVENT_AZALEA_TOWN_HIDDEN_FULL_HEAL
	const EVENT_CIANWOOD_CITY_HIDDEN_REVIVE
	const EVENT_CIANWOOD_CITY_HIDDEN_MAX_ETHER
	const EVENT_ECRUTEAK_CITY_HIDDEN_HYPER_POTION
	const EVENT_LAKE_OF_RAGE_HIDDEN_FULL_RESTORE
	const EVENT_LAKE_OF_RAGE_HIDDEN_RARE_CANDY
	const EVENT_LAKE_OF_RAGE_HIDDEN_MAX_POTION
	const EVENT_LAKE_OF_RAGE_OTIS
; Crystal-exclusive events in Johto
	const EVENT_MET_FLORIA
	const EVENT_TALKED_TO_FLORIA_AT_FLOWER_SHOP
	const EVENT_BUGGING_KURT_TOO_MUCH
	const EVENT_TALKED_TO_RUINS_COWARD
	const EVENT_GOT_DRATINI
	const EVENT_CAN_GIVE_GS_BALL_TO_KURT
	const EVENT_GAVE_GS_BALL_TO_KURT
	const EVENT_FOREST_IS_RESTLESS
	const EVENT_ANSWERED_DRAGON_MASTER_QUIZ_WRONG
	const EVENT_ROUTE_4_OTIS
	const EVENT_MET_RAJA
	const EVENT_DID_NOT_GET_BATTLE_LOBBY_PRIZE
	const EVENT_DID_NOT_GET_BATTLE_ARENA_PRIZE
	const EVENT_BATTLE_LOBBY_INVERSE_BATTLE
	const EVENT_BATTLE_LOBBY_TYPELESS_BATTLE
; Unused: next 0 events

	const_next 200
; Kanto story events
	const EVENT_TM_HIDDEN_POWER
	const EVENT_TM_HIDDEN_FORCE
	const EVENT_ROUTE_17_RAIKOU
	const EVENT_BURNED_TOWER_ENTEI
	const EVENT_MET_OTIS
	const EVENT_RESTORED_POWER_TO_KANTO
	const EVENT_GOT_START_MENU_WARP
	const EVENT_DID_NOT_GET_ECHO_CHAMBER_PRIZE
	const EVENT_MIRROR_CHRIS
	const EVENT_MIRROR_KRIS
	const EVENT_MR_POKEMON_TOGEPI_EGG
	const EVENT_ROUTE_6_HIDDEN_FOCUS_SASH
	const EVENT_TM_DARK_PULSE
	const EVENT_TM_FAIRY_FLASH
	const EVENT_ENABLE_DIPLOMA_PRINTING
	const_skip
	const_skip
	const_skip
	const EVENT_GOT_TM03_CURSE
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const EVENT_TALKED_TO_OAK_IN_KANTO
	const_skip
	const_skip
; Kanto hidden items
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const EVENT_MT_MORTAR_SQUARE_HIDDEN_MOON_STONE
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const EVENT_BURNED_TOWER_1F_HIDDEN_ULTRA_BALL
	const EVENT_BRENT_GOLD_BERRY
	const_skip
	const_skip
	const_skip
	const_skip
; Johto Frontier events
	const EVENT_MET_VIOLET
	const EVENT_CIANWOOD_GYM_BLOCKER
	const EVENT_MET_FOSSIL_SCIENTIST
	const EVENT_MET_TRADE_KID
	const EVENT_COMPLETED_TRADE_WITH_TRADE_BACK_KID
	const EVENT_PIKA_SURF
	const EVENT_RADIO_TOWER_5F_DIRECTOR_FAKE
	const EVENT_RADIO_TOWER_5F_REAL_DIRECTOR
	const EVENT_BATTLE_PLAZA_TM_MART_INTRO
	const EVENT_MET_EGG_TUTOR

; first 1000 step reset item
	const EVENT_ILEX_FOREST_TINY_MUSHROOM1
	const EVENT_ILEX_FOREST_TINY_MUSHROOM2
	const EVENT_ILEX_FOREST_LARGE_MUSHROOM
	const EVENT_ROUTE_1_APRICORN       ; PNK_APRICORN
	const EVENT_ROUTE_1_BERRY1         ; BERRY
	const EVENT_ROUTE_1_BERRY2         ; BERRY
	const EVENT_ROUTE_2_BERRY1         ; BERRY
	const EVENT_ROUTE_2_BERRY2         ; PSNCUREBERRY
	const EVENT_ROUTE_2_APRICORN1      ; YLW_APRICORN
	const EVENT_ROUTE_2_APRICORN2      ; GRN_APRICORN
	const EVENT_ROUTE_3_BERRY          ; BITTER_BERRY
	const EVENT_ROUTE_3_APRICORN       ; BLK_APRICORN
	const EVENT_VIOLET_CITY_BERRY1     ; PRZCUREBERRY
	const EVENT_VIOLET_CITY_BERRY2     ; BURNT_BERRY
	const EVENT_VIOLET_CITY_APRICORN_1 ; WHT_APRICORN
	const EVENT_VIOLET_CITY_APRICORN_2 ; BLK_APRICORN
	const EVENT_ROUTE_5_BERRY_1        ; PSNCUREBERRY
	const EVENT_ROUTE_5_BERRY_2        ; MINT_BERRY
	const EVENT_ROUTE_5_APRICORN_1     ; RED_APRICORN
	const EVENT_ROUTE_5_APRICORN_2     ; BLU_APRICORN
	const EVENT_ROUTE_5_APRICORN_3     ; GRN_APRICORN
	const EVENT_ROUTE_6_BERRY          ; MIRACLEBERRY
	const EVENT_ROUTE_6_APRICORN       ; WHT_APRICORN
	const EVENT_AZALEA_TOWN_APRICORN_1 ; WHT_APRICORN
	const EVENT_AZALEA_TOWN_APRICORN_2 ; BLK_APRICORN
	const EVENT_ROUTE_7_BERRY_1        ; MYSTERYBERRY
	const EVENT_ROUTE_7_APRICORN_1     ; BLU_APRICORN
	const EVENT_ROUTE_7_APRICORN_2     ; YLW_APRICORN
	const EVENT_ROUTE_7_APRICORN_3     ; RED_APRICORN
	const EVENT_ROUTE_8_BERRY_1        ; ICE_BERRY
	const EVENT_ROUTE_8_BERRY_2        ; BERRY
	const EVENT_ROUTE_8_APRICORN_1     ; PNK_APRICORN
	const EVENT_ROUTE_9_APRICORN_1     ; RED_APRICORN
	const EVENT_ROUTE_9_APRICORN_2     ; BLU_APRICORN
	const EVENT_ROUTE_9_APRICORN_3     ; YLW_APRICORN
	const EVENT_ROUTE_10_BERRY_1       ; BURNT_BERRY
	const EVENT_ROUTE_10_BERRY_2       ; MYSTERYBERRY
	const EVENT_ROUTE_11_BERRY_1       ; MINT_BERRY
	const EVENT_ROUTE_11_APRICORN_1    ; GRN_APRICORN
	const EVENT_ROUTE_14_APRICORN_1    ; PNK_APRICORN
	const EVENT_ROUTE_14_APRICORN_2    ; GRN_APRICORN
	const EVENT_ROUTE_14_APRICORN_3    ; YLW_APRICORN
	const EVENT_ROUTE_15_BERRY_1       ; BITTER_BERRY
	const EVENT_ROUTE_15_APRICORN_1    ; PNK_APRICORN
	const EVENT_ROUTE_16_BERRY_1       ; BURNT_BERRY
	const EVENT_ROUTE_16_BERRY_2       ; MIRACLEBERRY
	const EVENT_ROUTE_16_APRICORN_1    ; WHT_APRICORN
	const EVENT_ROUTE_17_BERRY_1       ; MYSTERYBERRY
	const EVENT_ROUTE_17_BERRY_2       ; MIRACLEBERRY
	const EVENT_ROUTE_17_BERRY_3       ; GOLD_BERRY
	const EVENT_ROUTE_18_BERRY_1       ; PRZCUREBERRY
	const EVENT_ROUTE_18_BERRY_2       ; BITTER_BERRY
	const EVENT_ROUTE_18_BERRY_3       ; BERRY
	const EVENT_ROUTE_18_BERRY_4       ; PSNCUREBERRY
	const EVENT_ROUTE_20_BERRY_1       ; GOLD_BERRY
	const EVENT_ROUTE_20_BERRY_2       ; MIRACLEBERRY
	const EVENT_ROUTE_20_BERRY_3       ; GOLD_BERRY
	const EVENT_ROUTE_20_BERRY_4       ; MIRACLEBERRY
	const EVENT_ROUTE_20_BERRY_5       ; MINT_BERRY
	const EVENT_ROUTE_20_APRICORN_1    ; RED_APRICORN
	const EVENT_ROUTE_20_APRICORN_2    ; BLU_APRICORN
; last 1000 step reset item

	const EVENT_ROUTE_2_BERRY_TEACHER
	const EVENT_MET_BATTLE_PLAZA_MOVE_TUTOR
	const EVENT_MET_DAY_CARE_GRANDDAUGHTER
	const EVENT_DAY_CARE_GRANDDAUGHTER_HAS_A_TINYMUSHROOM_FOR_PLAYER
	const EVENT_DAY_CARE_GRANDDAUGHTER_ADOPTS_AN_EGG
	const EVENT_DAY_CARE_GRANDDAUGHTER_THIS_IS_NOT_AN_EGG
	const EVENT_NATIONAL_PARK_GHOLDENGO
	const EVENT_BATTLE_TOWER_INVERSE_MODE
 	const EVENT_BATTLE_TOWER_TYPELESS_MODE
	const EVENT_BATTLE_POINTS_UNLOCKED

; volatile ability events
	const EVENT_REFLECT_BARRIER_PLAYER
	const EVENT_REFLECT_BARRIER_FOE
	const EVENT_LIGHT_BARRIER_PLAYER
	const EVENT_LIGHT_BARRIER_FOE
	const EVENT_INTIMIDATE_PLAYER
	const EVENT_INTIMIDATE_FOE
	const EVENT_ROCK_SNARE_PLAYER
	const EVENT_ROCK_SNARE_FOE
	const EVENT_CALTROPPER_PLAYER
	const EVENT_CALTROPPER_FOE
	const EVENT_VENOM_FIELD_PLAYER
	const EVENT_VENOM_FIELD_FOE
	const EVENT_SILK_SNARE_PLAYER
	const EVENT_SILK_SNARE_FOE
	const EVENT_CHRONO_SHIFT_PLAYER
	const EVENT_CHRONO_SHIFT_FOE
	const EVENT_FORTIFY_PLAYER
	const EVENT_FORTIFY_FOE
	const EVENT_IMPOSTER_PLAYER
	const EVENT_IMPOSTER_FOE
	const EVENT_INFERNAL_HOWL_PLAYER
	const EVENT_INFERNAL_HOWL_FOE
	const EVENT_BATTLE_STANCE_PLAYER
	const EVENT_BATTLE_STANCE_FOE
	const EVENT_BATTLE_DRIVE_PLAYER
	const EVENT_BATTLE_DRIVE_FOE
	const EVENT_TRUE_SIGHT_PLAYER
	const EVENT_TRUE_SIGHT_FOE
	const EVENT_FOG_OF_WAR_PLAYER
	const EVENT_FOG_OF_WAR_FOE
	const EVENT_DEFOG_PLAYER
	const EVENT_DEFOG_FOE
	const EVENT_CHAOTIC_BOOST_PLAYER
	const EVENT_CHAOTIC_BOOST_FOE
	const EVENT_SANCTUARY_PLAYER
	const EVENT_SANCTUARY_FOE
	const EVENT_SIEGEBREAKER_PLAYER
	const EVENT_SIEGEBREAKER_FOE
	const EVENT_PROVOCATEUR_PLAYER
	const EVENT_PROVOCATEUR_FOE
	const EVENT_DISARM_PLAYER
	const EVENT_DISARM_FOE
	const EVENT_ALLURE_PLAYER
	const EVENT_ALLURE_FOE

	const EVENT_CHEAT_MENU_ACCESSIBLE
	const EVENT_NEWBARK_CHEATER_KUN_EXITS
; Unused: next 209 events

	const_next 600
; Kurt Apricorn events
	const EVENT_GAVE_KURT_RED_APRICORN
	const EVENT_GAVE_KURT_BLU_APRICORN
	const EVENT_GAVE_KURT_YLW_APRICORN
	const EVENT_GAVE_KURT_GRN_APRICORN
	const EVENT_GAVE_KURT_WHT_APRICORN
	const EVENT_GAVE_KURT_BLK_APRICORN
	const EVENT_GAVE_KURT_PNK_APRICORN
; Phone events
	const EVENT_JACK_ASKED_FOR_PHONE_NUMBER
	const_skip
	const EVENT_BEVERLY_ASKED_FOR_PHONE_NUMBER
	const_skip
	const EVENT_HUEY_ASKED_FOR_PHONE_NUMBER
	const_skip
	const EVENT_GOT_PROTEIN_FROM_HUEY
	const_skip
	const EVENT_GOT_CARBOS_FROM_VANCE
	const_skip
	const_skip
	const_skip
	const EVENT_GAVEN_ASKED_FOR_PHONE_NUMBER
	const_skip
	const EVENT_BETH_ASKED_FOR_PHONE_NUMBER
	const_skip
	const EVENT_JOSE_ASKED_FOR_PHONE_NUMBER
	const_skip
	const EVENT_REENA_ASKED_FOR_PHONE_NUMBER
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const EVENT_TODD_ASKED_FOR_PHONE_NUMBER
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const EVENT_ARNIE_ASKED_FOR_PHONE_NUMBER
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const EVENT_DANA_ASKED_FOR_PHONE_NUMBER
	const_skip
	const EVENT_CHAD_ASKED_FOR_PHONE_NUMBER
	const_skip
	const EVENT_DEREK_ASKED_FOR_PHONE_NUMBER
	const_skip
	const EVENT_TULLY_ASKED_FOR_PHONE_NUMBER
	const_skip
	const EVENT_BRENT_ASKED_FOR_PHONE_NUMBER
	const_skip
	const EVENT_TIFFANY_ASKED_FOR_PHONE_NUMBER
	const_skip
	const EVENT_VANCE_ASKED_FOR_PHONE_NUMBER
	const_skip
	const EVENT_WILTON_ASKED_FOR_PHONE_NUMBER
	const_skip
	const EVENT_CHAD_TWISTEDSPOON
	const_skip
	const EVENT_PARRY_ASKED_FOR_PHONE_NUMBER
	const_skip
	const EVENT_ERIN_ASKED_FOR_PHONE_NUMBER
	const_skip
	const EVENT_ARNIE_SILVERPOWDER
; Ruins of Alph puzzles
	const EVENT_SOLVED_HO_OH_PUZZLE
	const EVENT_SOLVED_LILEEP_PUZZLE
	const EVENT_SOLVED_OMANYTE_PUZZLE
	const EVENT_SOLVED_AERODACTYL_PUZZLE
; Decorations
	const EVENT_DECO_BED_1
	const EVENT_DECO_BED_2
	const EVENT_DECO_BED_3
	const EVENT_DECO_BED_4
	const EVENT_DECO_CARPET_1
	const EVENT_DECO_CARPET_2
	const EVENT_DECO_CARPET_3
	const EVENT_DECO_CARPET_4
	const EVENT_DECO_PLANT_1
	const EVENT_DECO_PLANT_2
	const EVENT_DECO_PLANT_3
	const EVENT_DECO_POSTER_1
	const EVENT_DECO_POSTER_2
	const EVENT_DECO_POSTER_3
	const EVENT_DECO_POSTER_4
	const EVENT_DECO_FAMICOM
	const EVENT_DECO_SNES
	const EVENT_DECO_N64
	const EVENT_DECO_VIRTUAL_BOY
	const EVENT_DECO_PIKACHU_DOLL
	const EVENT_DECO_SURFING_PIKACHU_DOLL
	const EVENT_DECO_CLEFAIRY_DOLL
	const EVENT_DECO_JIGGLYPUFF_DOLL
	const EVENT_DECO_BULBASAUR_DOLL
	const EVENT_DECO_CHARMANDER_DOLL
	const EVENT_DECO_SQUIRTLE_DOLL
	const EVENT_DECO_POLIWAG_DOLL
	const EVENT_DECO_TANGELA_DOLL
	const EVENT_DECO_STARYU_DOLL
	const EVENT_DECO_MAGIKARP_DOLL
	const EVENT_DECO_ODDISH_DOLL
	const EVENT_DECO_GENGAR_DOLL
	const EVENT_DECO_SHELLDER_DOLL
	const EVENT_DECO_GRIMER_DOLL
	const EVENT_DECO_VOLTORB_DOLL
	const EVENT_DECO_WEEDLE_DOLL
	const EVENT_DECO_UNOWN_DOLL
	const EVENT_DECO_GEODUDE_DOLL
	const EVENT_DECO_HARIYAMA_DOLL
	const EVENT_DECO_TENTACOOL_DOLL
	const EVENT_PLAYERS_ROOM_POSTER
	const EVENT_DECO_GOLD_TROPHY
	const EVENT_DECO_SILVER_TROPHY
	const EVENT_DECO_BIG_SNORLAX_DOLL
	const EVENT_DECO_BIG_ONIX_DOLL
	const EVENT_DECO_BIG_LAPRAS_DOLL
; More Johto story events
	const EVENT_WARPED_FROM_ROUTE_7_NATIONAL_PARK_GATE
	const EVENT_SWITCH_1
	const EVENT_SWITCH_2
	const EVENT_SWITCH_3
	const EVENT_EMERGENCY_SWITCH
	const EVENT_SWITCH_4
	const EVENT_SWITCH_5
	const EVENT_SWITCH_6
	const EVENT_SWITCH_7
	const EVENT_SWITCH_8
	const EVENT_SWITCH_9
	const EVENT_SWITCH_10
	const EVENT_SWITCH_11
	const EVENT_SWITCH_12
	const EVENT_SWITCH_13
	const EVENT_SWITCH_14
	const EVENT_UNCOVERED_STAIRCASE_IN_MAHOGANY_MART
	const EVENT_TURNED_OFF_SECURITY_CAMERAS
	const EVENT_SECURITY_CAMERA_1
	const EVENT_SECURITY_CAMERA_2
	const EVENT_SECURITY_CAMERA_3
	const EVENT_SECURITY_CAMERA_4
	const EVENT_SECURITY_CAMERA_5
	const EVENT_EXPLODING_TRAP_1
	const EVENT_EXPLODING_TRAP_2
	const EVENT_EXPLODING_TRAP_3
	const EVENT_EXPLODING_TRAP_4
	const EVENT_EXPLODING_TRAP_5
	const EVENT_EXPLODING_TRAP_6
	const EVENT_EXPLODING_TRAP_7
	const EVENT_EXPLODING_TRAP_8
	const EVENT_EXPLODING_TRAP_9
	const EVENT_EXPLODING_TRAP_10
	const EVENT_EXPLODING_TRAP_11
	const EVENT_EXPLODING_TRAP_12
	const EVENT_EXPLODING_TRAP_13
	const EVENT_EXPLODING_TRAP_14
	const EVENT_EXPLODING_TRAP_15
	const EVENT_EXPLODING_TRAP_16
	const EVENT_EXPLODING_TRAP_17
	const EVENT_EXPLODING_TRAP_18
	const EVENT_EXPLODING_TRAP_19
	const EVENT_EXPLODING_TRAP_20
	const EVENT_EXPLODING_TRAP_21
	const EVENT_EXPLODING_TRAP_22
	const EVENT_LEARNED_HAIL_GIOVANNI
	const EVENT_OPENED_DOOR_TO_ROCKET_HIDEOUT_TRANSMITTER
	const EVENT_LEARNED_SLOWPOKETAIL
	const EVENT_LEARNED_RATICATE_TAIL
	const EVENT_OPENED_DOOR_TO_GIOVANNIS_OFFICE
	const_skip
	const_skip
	const_skip
	const_skip
	const EVENT_LEFT_MONS_WITH_CONTEST_OFFICER
	const EVENT_WILLS_ROOM_ENTRANCE_CLOSED
	const EVENT_WILLS_ROOM_EXIT_OPEN
	const EVENT_KOGAS_ROOM_ENTRANCE_CLOSED
	const EVENT_KOGAS_ROOM_EXIT_OPEN
	const EVENT_BRUNOS_ROOM_ENTRANCE_CLOSED
	const EVENT_BRUNOS_ROOM_EXIT_OPEN
	const EVENT_KARENS_ROOM_ENTRANCE_CLOSED
	const EVENT_KARENS_ROOM_EXIT_OPEN
	const EVENT_LANCES_ROOM_ENTRANCE_CLOSED
	const EVENT_LANCES_ROOM_EXIT_OPEN
	const EVENT_CONTEST_OFFICER_HAS_SUN_STONE
	const EVENT_CONTEST_OFFICER_HAS_MOON_STONE
	const EVENT_CONTEST_OFFICER_HAS_GOLD_BERRY
	const EVENT_CONTEST_OFFICER_HAS_BERRY
	const EVENT_FOUGHT_HO_OH
	const EVENT_FOUGHT_LUGIA
	const EVENT_REENA_MOON_STONE
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const EVENT_LISTENED_TO_INITIAL_RADIO
; More Crystal-exclusive events in Johto
	const EVENT_WALL_OPENED_IN_HO_OH_CHAMBER
	const EVENT_WALL_OPENED_IN_LILEEP_CHAMBER
	const EVENT_WALL_OPENED_IN_OMANYTE_CHAMBER
	const EVENT_WALL_OPENED_IN_AERODACTYL_CHAMBER
	const EVENT_WELCOMED_TO_POKECOM_CENTER
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const EVENT_HOLE_IN_BURNED_TOWER
	const EVENT_FOUGHT_EUSINE
	const EVENT_KOJI_ALLOWS_YOU_PASSAGE_TO_TIN_TOWER
	const EVENT_FOUGHT_SUICUNE
	const EVENT_GOT_RAINBOW_WING
	const EVENT_JACK_ZINC
	const_skip
	const EVENT_VANCE_CARBOS
	const EVENT_PARRY_IRON
	const EVENT_ERIN_CALCIUM
	const_skip
	const EVENT_MET_BUENA
	const EVENT_GOT_ODD_EGG
	const EVENT_GAVEN_CRYSTAL
	const EVENT_BETH_RARE_CANDY
; Unused: next 167 events

	const_next 1000
; Trainer flags
; Swimmer F
	const EVENT_BEAT_SWIMMERF_ELAINE
	const EVENT_BEAT_SWIMMERF_PAULA
	const EVENT_BEAT_SWIMMERF_KAYLEE
	const EVENT_BEAT_SWIMMERF_SUSIE
	const EVENT_BEAT_SWIMMERF_DENISE
	const EVENT_BEAT_SWIMMERF_KARA
	const EVENT_BEAT_SWIMMERF_WENDY
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
; Bird Keeper
	const EVENT_BEAT_BIRD_KEEPER_ROD
	const EVENT_BEAT_BIRD_KEEPER_ABE
	const EVENT_BEAT_BIRD_KEEPER_BRYAN
	const EVENT_BEAT_BIRD_KEEPER_THEO
	const EVENT_BEAT_BIRD_KEEPER_TOBY
	const EVENT_BEAT_BIRD_KEEPER_DENIS
	const EVENT_BEAT_BIRD_KEEPER_VANCE
	const_skip
	const_skip
	const_skip
	const_skip
	const EVENT_BEAT_BIRD_KEEPER_JOSE
	const EVENT_BEAT_BIRD_KEEPER_PETER
	const EVENT_BEAT_BIRD_KEEPER_JOSE2
	const_skip
	const_skip
	const EVENT_BEAT_BIRD_KEEPER_JOSE3
	const EVENT_BEAT_BIRD_KEEPER_VANCE2
	const EVENT_BEAT_BIRD_KEEPER_VANCE3
; Boarder
	const EVENT_BEAT_BOARDER_RONALD
	const EVENT_BEAT_BOARDER_BRAD
	const EVENT_BEAT_BOARDER_DOUGLAS
; Sage
	const EVENT_BEAT_SAGE_CHOW
	const EVENT_BEAT_SAGE_NICO
	const EVENT_BEAT_SAGE_JIN
	const EVENT_BEAT_SAGE_TROY
	const EVENT_BEAT_SAGE_JEFFREY
	const EVENT_BEAT_SAGE_PING
	const EVENT_BEAT_SAGE_EDMOND
	const EVENT_BEAT_SAGE_NEAL
	const_skip
; Camper
	const EVENT_BEAT_CAMPER_ROLAND
	const EVENT_BEAT_CAMPER_TODD
	const EVENT_BEAT_CAMPER_IVAN
	const EVENT_BEAT_CAMPER_ELLIOT
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const EVENT_BEAT_CAMPER_TED
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const EVENT_BEAT_CAMPER_SPENCER
; Burglar
	const EVENT_BEAT_BURGLAR_DUNCAN
	const EVENT_BEAT_BURGLAR_EDDIE
	const_skip
	const_skip
; Biker
	const EVENT_BEAT_BIKER_BENNY
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
; Psychic
	const EVENT_BEAT_PSYCHIC_NATHAN
	const_skip
	const_skip
	const_skip
	const EVENT_BEAT_PSYCHIC_GREG
	const EVENT_BEAT_PSYCHIC_NORMAN
	const EVENT_BEAT_PSYCHIC_MARK
	const EVENT_BEAT_PSYCHIC_PHIL
	const EVENT_BEAT_PSYCHIC_RICHARD
	const EVENT_BEAT_PSYCHIC_GILBERT
	const_skip
	const_skip
; Firebreather
	const_skip
	const_skip
	const_skip
	const_skip
	const EVENT_BEAT_FIREBREATHER_BILL
	const EVENT_BEAT_FIREBREATHER_WALT
	const EVENT_BEAT_FIREBREATHER_RAY
	const_skip
; Fisher
	const EVENT_BEAT_FISHER_JUSTIN
	const EVENT_BEAT_FISHER_RALPH
	const_skip
	const_skip
	const EVENT_BEAT_FISHER_HENRY
	const EVENT_BEAT_FISHER_MARVIN
	const EVENT_BEAT_FISHER_TULLY
	const EVENT_BEAT_FISHER_ANDRE
	const EVENT_BEAT_FISHER_RAYMOND
	const EVENT_BEAT_FISHER_WILTON
	const EVENT_BEAT_FISHER_EDGAR
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const EVENT_BEAT_FISHER_TULLY2
	const EVENT_BEAT_FISHER_TULLY3
	const EVENT_BEAT_FISHER_WILTON2
	const EVENT_BEAT_FISHER_SCOTT
	const EVENT_BEAT_FISHER_WILTON3
; Twins
	const EVENT_BEAT_TWINS_AMY_AND_MAY
	const EVENT_BEAT_TWINS_ANN_AND_ANNE
	const EVENT_BEAT_TWINS_ANN_AND_ANNE2
	const EVENT_BEAT_TWINS_AMY_AND_MAY2
	const_skip
	const_skip
	const_skip
	const_skip
; Schoolboy
	const EVENT_BEAT_SCHOOLBOY_JACK
	const_skip
	const EVENT_BEAT_SCHOOLBOY_ALAN
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const EVENT_BEAT_SCHOOLBOY_CHAD
	const_skip
	const_skip
	const EVENT_BEAT_SCHOOLBOY_JACK2
	const EVENT_BEAT_SCHOOLBOY_JACK3
	const_skip
	const_skip
	const EVENT_BEAT_SCHOOLBOY_CHAD2
	const EVENT_BEAT_SCHOOLBOY_CHAD3
; Picnicker
	const EVENT_BEAT_PICNICKER_LIZ
	const EVENT_BEAT_PICNICKER_GINA
	const EVENT_BEAT_PICNICKER_BROOKE
	const EVENT_BEAT_PICNICKER_KIM
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const EVENT_BEAT_PICNICKER_ERIN
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const EVENT_BEAT_PICNICKER_TIFFANY2
	const EVENT_BEAT_PICNICKER_TIFFANY3
	const EVENT_BEAT_PICNICKER_ERIN2
	const_skip
	const EVENT_BEAT_PICNICKER_TIFFANY
	const EVENT_BEAT_PICNICKER_ERIN3
; Guitarist
	const_skip
	const_skip
; Juggler
	const EVENT_BEAT_JUGGLER_IRWIN
	const_skip
	const_skip
	const_skip
	const_skip
; Gentleman
	const EVENT_BEAT_GENTLEMAN_PRESTON
	const EVENT_BEAT_GENTLEMAN_CHARLES
	const_skip
	const_skip
	const EVENT_BEAT_GENTLEMAN_ALFRED
; Scientist
	const EVENT_BEAT_SCIENTIST_ROSS
	const EVENT_BEAT_SCIENTIST_MITCH
	const EVENT_BEAT_SCIENTIST_JED
	const EVENT_BEAT_SCIENTIST_MARC
	const EVENT_BEAT_SCIENTIST_RICH
; Blackbelt
	const_skip
	const EVENT_BEAT_BLACKBELT_YOSHI
	const_skip
	const EVENT_BEAT_BLACKBELT_LAO
	const EVENT_BEAT_SAILOR_STEELE
	const EVENT_BEAT_BLACKBELT_KIYO
	const EVENT_BEAT_BLACKBELT_LUNG
	const EVENT_BEAT_BLACKBELT_KENJI
	const_skip
; Beauty
	const EVENT_BEAT_BEAUTY_VICTORIA
	const EVENT_BEAT_BEAUTY_SAMANTHA
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const EVENT_BEAT_BEAUTY_VALERIE
; Johto Gym Leaders
	const EVENT_BEAT_FALKNER
	const EVENT_BEAT_BUGSY
	const EVENT_BEAT_WHITNEY
	const EVENT_BEAT_MORTY
	const EVENT_BEAT_JASMINE
	const EVENT_BEAT_CHUCK
	const EVENT_BEAT_PRYCE
	const EVENT_BEAT_CLAIR
; Kanto Gym Leaders
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
; PokefanM
	const EVENT_BEAT_POKEFANM_WILLIAM
	const EVENT_BEAT_POKEFANM_DEREK
	const_skip
	const_skip
	const_skip
	const_skip
	const EVENT_BEAT_POKEFANM_BRANDON
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
; PokefanF
	const EVENT_BEAT_POKEFANF_BEVERLY
	const EVENT_BEAT_POKEFANF_RUTH
	const_skip
	const_skip
	const_skip
; Kimono Girl
	const_skip
	const EVENT_BEAT_KIMONO_GIRL_NAOKO
	const EVENT_BEAT_KIMONO_GIRL_SAYO
	const EVENT_BEAT_KIMONO_GIRL_ZUKI
	const EVENT_BEAT_KIMONO_GIRL_KUNI
	const EVENT_BEAT_KIMONO_GIRL_MIKI
; Pokemaniac
	const EVENT_BEAT_POKEMANIAC_LARRY
	const EVENT_BEAT_POKEMANIAC_ANDREW
	const EVENT_BEAT_POKEMANIAC_CALVIN
	const EVENT_BEAT_POKEMANIAC_SHANE
	const EVENT_BEAT_POKEMANIAC_BEN
	const EVENT_BEAT_POKEMANIAC_BRENT
	const EVENT_BEAT_POKEMANIAC_RON
	const_skip
	const EVENT_BEAT_POKEMANIAC_BRENT2
	const EVENT_BEAT_POKEMANIAC_BRENT3
	const EVENT_BEAT_POKEMANIAC_ISSAC
	const EVENT_BEAT_POKEMANIAC_DONALD
	const EVENT_BEAT_POKEMANIAC_ZACH
; GruntM
	const_skip
	const_skip
	const EVENT_BEAT_ROCKET_GRUNTM_3
	const EVENT_BEAT_ROCKET_GRUNTM_4
	const EVENT_BEAT_ROCKET_GRUNTM_5
	const EVENT_BEAT_ROCKET_GRUNTM_6
	const EVENT_BEAT_ROCKET_GRUNTM_7
	const EVENT_BEAT_ROCKET_GRUNTM_8
	const EVENT_BEAT_ROCKET_GRUNTM_9
	const EVENT_BEAT_ROCKET_GRUNTM_10
	const EVENT_BEAT_ROCKET_GRUNTM_11
	const_skip
	const EVENT_BEAT_ROCKET_GRUNTM_13
	const EVENT_BEAT_ROCKET_GRUNTM_14
	const EVENT_BEAT_ROCKET_GRUNTM_15
	const EVENT_BEAT_ROCKET_GRUNTM_16
	const EVENT_BEAT_ROCKET_GRUNTM_17
	const EVENT_BEAT_ROCKET_GRUNTM_18
	const EVENT_BEAT_ROCKET_GRUNTM_19
	const EVENT_BEAT_ROCKET_GRUNTM_20
	const EVENT_BEAT_ROCKET_GRUNTM_21
	const_skip
	const_skip
	const EVENT_BEAT_ROCKET_GRUNTM_24
	const EVENT_BEAT_ROCKET_GRUNTM_25
	const EVENT_BEAT_ROCKET_GRUNTM_28
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
; GruntF
	const_skip
	const EVENT_BEAT_ROCKET_GRUNTF_2
	const EVENT_BEAT_ROCKET_GRUNTF_3
	const EVENT_BEAT_ROCKET_GRUNTF_4
	const EVENT_BEAT_ROCKET_GRUNTF_5
; Lass
	const EVENT_BEAT_LASS_CARRIE
	const EVENT_BEAT_LASS_BRIDGET
	const EVENT_BEAT_LASS_SELINA
	const EVENT_BEAT_LASS_KRISE
	const EVENT_BEAT_LASS_CONNIE
	const EVENT_BEAT_SCHOOLBOY_LIAM
	const EVENT_BEAT_COOLTRAINERM_KYLE
	const_skip
	const_skip
	const EVENT_BEAT_LASS_DANA
	const_skip
	const_skip
	const_skip
	const EVENT_BEAT_LASS_DANA2
	const EVENT_BEAT_LASS_DANA3
; Hiker
	const_skip
	const EVENT_BEAT_HIKER_RUSSELL
	const EVENT_BEAT_HIKER_PHILLIP
	const EVENT_BEAT_HIKER_LEONARD
	const EVENT_BEAT_HIKER_ANTHONY
	const EVENT_BEAT_HIKER_BENJAMIN
	const EVENT_BEAT_HIKER_ERIK
	const EVENT_BEAT_HIKER_MICHAEL
	const EVENT_BEAT_HIKER_PARRY
	const EVENT_BEAT_HIKER_TIMOTHY
	const EVENT_BEAT_HIKER_BAILEY
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const EVENT_BEAT_HIKER_DANIEL
	const EVENT_BEAT_HIKER_PARRY2
	const EVENT_BEAT_HIKER_PARRY3
; Bug Catcher
	const EVENT_BEAT_BUG_CATCHER_DON
	const EVENT_BEAT_BUG_CATCHER_EMMANUEL
	const EVENT_BEAT_BUG_CATCHER_ADAM
	const EVENT_BEAT_BUG_CATCHER_WADE
	const EVENT_BEAT_BUG_CATCHER_BENNY
	const EVENT_BEAT_BUG_CATCHER_AL
	const EVENT_BEAT_BUG_CATCHER_JOSH
	const EVENT_BEAT_BUG_CATCHER_ARNIE
	const_skip
	const_skip
	const_skip
	const_skip
	const EVENT_BEAT_BUG_CATCHER_ARNIE2
	const EVENT_BEAT_BUG_CATCHER_ARNIE3
; Officer
	const EVENT_BEAT_OFFICER_KEITH
	const EVENT_BEAT_OFFICER_DIRK
; CooltrainerM
	const EVENT_BEAT_COOLTRAINERM_NICK
	const EVENT_BEAT_COOLTRAINERM_AARON
	const EVENT_BEAT_COOLTRAINERM_PAUL
	const EVENT_BEAT_COOLTRAINERM_CODY
	const EVENT_BEAT_COOLTRAINERM_MIKE
	const EVENT_BEAT_COOLTRAINERM_GAVEN2
	const EVENT_BEAT_COOLTRAINERM_GAVEN3
	const EVENT_BEAT_COOLTRAINERM_RYAN
	const EVENT_BEAT_COOLTRAINERM_JAKE
	const EVENT_BEAT_COOLTRAINERM_GAVEN
	const EVENT_BEAT_COOLTRAINERM_BLAKE
	const EVENT_BEAT_COOLTRAINERM_BRIAN
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const EVENT_BEAT_COOLTRAINERM_ALLEN
; CooltrainerF
	const EVENT_BEAT_COOLTRAINERF_GWEN
	const EVENT_BEAT_COOLTRAINERF_LOIS
	const EVENT_BEAT_COOLTRAINERF_FRAN
	const EVENT_BEAT_COOLTRAINERF_LOLA
	const EVENT_BEAT_COOLTRAINERF_KATE
	const EVENT_BEAT_COOLTRAINERF_IRENE
	const EVENT_BEAT_COOLTRAINERF_KELLY
	const EVENT_BEAT_COOLTRAINERF_JOYCE
	const EVENT_BEAT_COOLTRAINERF_BETH
	const EVENT_BEAT_COOLTRAINERF_REENA
	const EVENT_BEAT_COOLTRAINERF_MEGAN
	const EVENT_BEAT_COOLTRAINERF_BETH2
	const_skip
	const_skip
	const EVENT_BEAT_COOLTRAINERF_EMMA
	const EVENT_BEAT_COOLTRAINERF_CYBIL
	const EVENT_BEAT_COOLTRAINERF_JENN
	const EVENT_BEAT_COOLTRAINERF_BETH3
	const EVENT_BEAT_COOLTRAINERF_REENA2
	const EVENT_BEAT_COOLTRAINERF_REENA3
; ExecutiveF
	const EVENT_BEAT_ROCKET_EXECUTIVEF_1
	const EVENT_BEAT_ROCKET_EXECUTIVEF_2
; ExecutiveM
	const EVENT_BEAT_ROCKET_EXECUTIVEM_1
	const EVENT_BEAT_ROCKET_EXECUTIVEM_2
	const EVENT_BEAT_ROCKET_EXECUTIVEM_3
	const EVENT_BEAT_ROCKET_EXECUTIVEM_4
; Sailor
	const EVENT_BEAT_SAILOR_EUGENE
	const EVENT_BEAT_SAILOR_HUEY
	const EVENT_BEAT_SAILOR_TERRELL
	const EVENT_BEAT_SAILOR_KENT
	const EVENT_BEAT_SAILOR_ERNEST
	const_skip
	const_skip
	const_skip
	const_skip
	const EVENT_BEAT_SAILOR_HARRY
	const EVENT_BEAT_SAILOR_HUEY2
	const EVENT_BEAT_SAILOR_HUEY3
; Super Nerd
	const EVENT_BEAT_SUPER_NERD_STAN
	const EVENT_BEAT_SUPER_NERD_ERIC
	const EVENT_BEAT_SUPER_NERD_TONY
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const EVENT_BEAT_SUPER_NERD_TERU
; Medium
	const EVENT_BEAT_MEDIUM_MARTHA
	const EVENT_BEAT_MEDIUM_GRACE
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
; Skier
	const EVENT_BEAT_SKIER_ROXANNE
	const EVENT_BEAT_SKIER_CLARISSA
; SwimmerM
	const_skip
	const EVENT_BEAT_SWIMMERM_SIMON
	const EVENT_BEAT_SWIMMERM_RANDALL
	const EVENT_BEAT_SWIMMERM_CHARLIE
	const EVENT_BEAT_SWIMMERM_GEORGE
	const EVENT_BEAT_SWIMMERM_BERKE
	const EVENT_BEAT_SWIMMERM_KIRK
	const EVENT_BEAT_SWIMMERM_MATHEW
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
; Youngster
	const EVENT_BEAT_YOUNGSTER_JOEY
	const EVENT_BEAT_YOUNGSTER_MIKEY
	const EVENT_BEAT_YOUNGSTER_ALBERT
	const EVENT_BEAT_YOUNGSTER_GORDON
	const EVENT_BEAT_YOUNGSTER_SAMUEL
	const EVENT_BEAT_YOUNGSTER_IAN
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
; Teacher
	const_skip
	const_skip
	const_skip
; Elite Four and Champion
	const EVENT_BEAT_ELITE_4_WILL
	const EVENT_BEAT_ELITE_4_KOGA
	const EVENT_BEAT_ELITE_4_BRUNO
	const EVENT_BEAT_ELITE_4_KAREN
	const EVENT_BEAT_CHAMPION_LANCE
; Crystal-exclusive trainer flags
	const EVENT_BEAT_COOLTRAINERM_DARIN
	const EVENT_BEAT_COOLTRAINERF_CARA
	const EVENT_BEAT_TWINS_LEA_AND_PIA
	const EVENT_BEAT_BUG_CATCHER_WAYNE
	const EVENT_BEAT_BEAUTY_OLIVIA
	const EVENT_BEAT_POKEFANF_JAIME
	const EVENT_BEAT_CAMPER_QUENTIN
	const EVENT_BEAT_POKEMANIAC_MILLER
	const EVENT_BEAT_SUPER_NERD_HUGH
	const EVENT_BEAT_SUPER_NERD_MARKUS
	const_skip
	const_skip
	const EVENT_BEAT_SAGE_GAKU
	const EVENT_BEAT_SAGE_MASA
	const EVENT_BEAT_SAGE_KOJI
; Unused: next 116 events

	const_next 1600
; Sprite visibility flags
; When these events are cleared, the sprite becomes visible; when set, the sprite is hidden.
; The map script command macros `disappear` and `appear` set/clear these flags and immediately apply the effect on visibility.
; The map script command macros `setevent` and `clearevent` set/clear these flags, and their effects will be seen when the map is reloaded.
; Johto itemballs
	const EVENT_CYNDAQUIL_POKEBALL_IN_ELMS_LAB
	const EVENT_TOTODILE_POKEBALL_IN_ELMS_LAB
	const EVENT_CHIKORITA_POKEBALL_IN_ELMS_LAB
	const EVENT_VIOLET_CITY_PP_UP
	const EVENT_VIOLET_CITY_RARE_CANDY
	const EVENT_LAKE_OF_RAGE_ELIXER
	const EVENT_LAKE_OF_RAGE_TM_DETECT
	const EVENT_SPROUT_TOWER_1F_PARLYZ_HEAL
	const EVENT_SPROUT_TOWER_2F_X_ACCURACY
	const EVENT_SPROUT_TOWER_3F_POTION
	const EVENT_SPROUT_TOWER_3F_ESCAPE_ROPE
	const EVENT_TIN_TOWER_3F_FULL_HEAL
	const EVENT_TIN_TOWER_4F_ULTRA_BALL
	const EVENT_TIN_TOWER_4F_PP_UP
	const EVENT_TIN_TOWER_4F_ESCAPE_ROPE
	const EVENT_TIN_TOWER_5F_RARE_CANDY
	const EVENT_TIN_TOWER_7F_MAX_REVIVE
	const EVENT_TIN_TOWER_8F_NUGGET
	const EVENT_TIN_TOWER_8F_MAX_ELIXER
	const EVENT_TIN_TOWER_8F_FULL_RESTORE
	const EVENT_TEAM_ROCKET_BASE_B3F_ULTRA_BALL
	const EVENT_GOLDENROD_UNDERGROUND_WAREHOUSE_ULTRA_BALL
	const EVENT_BURNED_TOWER_1F_HP_UP
	const EVENT_BURNED_TOWER_B1F_TM_ENDURE
	const EVENT_NATIONAL_PARK_PARLYZ_HEAL
	const EVENT_NATIONAL_PARK_TM_DIG
	const EVENT_UNION_CAVE_1F_GREAT_BALL
	const EVENT_UNION_CAVE_1F_X_ATTACK
	const EVENT_UNION_CAVE_1F_POTION
	const EVENT_UNION_CAVE_1F_AWAKENING
	const EVENT_UNION_CAVE_B1F_TM_SWIFT
	const EVENT_UNION_CAVE_B1F_SUN_SHARD
	const EVENT_UNION_CAVE_B2F_ELIXER
	const EVENT_UNION_CAVE_B2F_HYPER_POTION
	const EVENT_SLOWPOKE_WELL_B1F_SUPER_POTION
	const EVENT_SLOWPOKE_WELL_B2F_TM_RAIN_DANCE
	const EVENT_OLIVINE_LIGHTHOUSE_3F_ETHER
	const EVENT_OLIVINE_LIGHTHOUSE_5F_RARE_CANDY
	const EVENT_OLIVINE_LIGHTHOUSE_5F_SUPER_REPEL
	const EVENT_OLIVINE_LIGHTHOUSE_5F_TM_SWAGGER
	const EVENT_OLIVINE_LIGHTHOUSE_6F_SUPER_POTION
	const EVENT_TEAM_ROCKET_BASE_B1F_HYPER_POTION
	const EVENT_TEAM_ROCKET_BASE_B1F_NUGGET
	const EVENT_TEAM_ROCKET_BASE_B1F_GUARD_SPEC
	const EVENT_TEAM_ROCKET_BASE_B2F_TM_THIEF
	const EVENT_TEAM_ROCKET_BASE_B3F_PROTEIN
	const EVENT_TEAM_ROCKET_BASE_B3F_X_SPECIAL
	const EVENT_TEAM_ROCKET_BASE_B3F_FULL_HEAL
	const EVENT_TEAM_ROCKET_BASE_B3F_ICE_HEAL
	const EVENT_ILEX_FOREST_REVIVE
	const EVENT_GOLDENROD_UNDERGROUND_COIN_CASE
	const EVENT_GOLDENROD_UNDERGROUND_SWITCH_ROOM_ENTRANCES_SMOKE_BALL
	const EVENT_GOLDENROD_UNDERGROUND_SWITCH_ROOM_ENTRANCES_FULL_HEAL
	const EVENT_GOLDENROD_DEPT_STORE_B1F_MAX_ETHER
	const EVENT_GOLDENROD_DEPT_STORE_B1F_AMULET_COIN
	const EVENT_GOLDENROD_DEPT_STORE_B1F_FULL_HEAL
	const EVENT_GOLDENROD_DEPT_STORE_B1F_ULTRA_BALL
	const EVENT_GOLDENROD_UNDERGROUND_WAREHOUSE_MAX_ETHER
	const EVENT_GOLDENROD_UNDERGROUND_WAREHOUSE_TM_SLEEP_TALK
	const EVENT_MOUNT_MORTAR_1F_OUTSIDE_ETHER
	const EVENT_MOUNT_MORTAR_1F_OUTSIDE_REVIVE
	const EVENT_MOUNT_MORTAR_1F_INSIDE_ESCAPE_ROPE
	const EVENT_MOUNT_MORTAR_1F_INSIDE_MAX_REVIVE
	const EVENT_MOUNT_MORTAR_1F_INSIDE_HYPER_POTION
	const EVENT_MOUNT_MORTAR_2F_INSIDE_MAX_POTION
	const EVENT_MOUNT_MORTAR_2F_INSIDE_RARE_CANDY
	const EVENT_MOUNT_MORTAR_2F_INSIDE_TM_DEFENSE_CURL
	const EVENT_MOUNT_MORTAR_2F_INSIDE_DRAGON_SCALE
	const EVENT_MOUNT_MORTAR_2F_INSIDE_ELIXER
	const EVENT_MOUNT_MORTAR_2F_INSIDE_ESCAPE_ROPE
	const EVENT_MOUNT_MORTAR_B1F_HYPER_POTION
	const EVENT_MOUNT_MORTAR_B1F_CARBOS
	const EVENT_GOT_MILOTIC_CALL
	const EVENT_ICE_PATH_1F_PP_UP
	const EVENT_ICE_PATH_B1F_IRON
	const EVENT_ICE_PATH_B2F_MAHOGANY_SIDE_FULL_HEAL
	const EVENT_ICE_PATH_B2F_MAHOGANY_SIDE_MAX_POTION
	const EVENT_ICE_PATH_B2F_BLACKTHORN_SIDE_TM_REST
	const EVENT_ICE_PATH_B3F_NEVERMELTICE
	const EVENT_WHIRL_ISLAND_NE_ULTRA_BALL
	const EVENT_WHIRL_ISLAND_SW_ULTRA_BALL
	const EVENT_WHIRL_ISLAND_B1F_FULL_RESTORE
	const EVENT_WHIRL_ISLAND_B1F_CARBOS
	const EVENT_WHIRL_ISLAND_B1F_CALCIUM
	const EVENT_WHIRL_ISLAND_B1F_NUGGET
	const EVENT_WHIRL_ISLAND_B1F_ESCAPE_ROPE
	const EVENT_WHIRL_ISLAND_B2F_FULL_RESTORE
	const EVENT_WHIRL_ISLAND_B2F_MAX_REVIVE
	const EVENT_WHIRL_ISLAND_B2F_MAX_ELIXER
	const EVENT_SILVER_CAVE_ROOM_1_MAX_ELIXER
	const EVENT_SILVER_CAVE_ROOM_1_PROTEIN
	const EVENT_SILVER_CAVE_ROOM_1_ESCAPE_ROPE
	const EVENT_SILVER_CAVE_ITEM_ROOMS_MAX_REVIVE
	const EVENT_SILVER_CAVE_ITEM_ROOMS_FULL_RESTORE
	const EVENT_DARK_CAVE_VIOLET_ENTRANCE_POTION
	const EVENT_DARK_CAVE_VIOLET_ENTRANCE_FULL_HEAL
	const EVENT_DARK_CAVE_VIOLET_ENTRANCE_HYPER_POTION
	const EVENT_DARK_CAVE_BLACKTHORN_ENTRANCE_REVIVE
	const EVENT_DARK_CAVE_BLACKTHORN_ENTRANCE_TM_SNORE
	const EVENT_VICTORY_ROAD_TM_EARTHQUAKE
	const EVENT_VICTORY_ROAD_MAX_REVIVE
	const EVENT_VICTORY_ROAD_FULL_RESTORE
	const EVENT_VICTORY_ROAD_FULL_HEAL
	const EVENT_VICTORY_ROAD_SACRED_ASH
	const EVENT_DRAGONS_DEN_B1F_DRAGON_FANG
	const EVENT_TOHJO_FALLS_MOON_STONE
	const EVENT_ROUTE_20_MAX_ELIXER
	const EVENT_ROUTE_19_TM_SOLARBEAM
	const EVENT_ROUTE_19_RARE_CANDY
	const EVENT_ROUTE_1_POTION
	const EVENT_ROUTE_3_POTION
	const EVENT_ROUTE_3_POKE_BALL
	const EVENT_ROUTE_4_GREAT_BALL
	const EVENT_ROUTE_4_REPEL
	const EVENT_ROUTE_7_TM_ROLLOUT
	const EVENT_ROUTE_14_ULTRA_BALL
	const EVENT_ROUTE_14_SUPER_POTION
	const EVENT_ROUTE_15_MAX_ETHER
	const EVENT_ROUTE_16_MAX_REVIVE
	const EVENT_ROUTE_16_ULTRA_BALL
	const EVENT_ROUTE_17_OTIS
	const EVENT_ROUTE_17_REVIVE
	const EVENT_ROUTE_17_ELIXER
	const EVENT_ROUTE_17_MAX_POTION
	const EVENT_ROUTE_18_X_SPEED
; Johto people
	const_skip
	const_skip
	const_skip
	const EVENT_RIVAL_TEAM_ROCKET_BASE
	const EVENT_RIVAL_GOLDENROD_UNDERGROUND
	const EVENT_RIVAL_VICTORY_ROAD
	const EVENT_RIVAL_OLIVINE_CITY
	const_skip
	const EVENT_RIVAL_BURNED_TOWER
	const EVENT_RIVAL_DRAGONS_DEN
	const EVENT_PLAYERS_HOUSE_MOM_1
	const EVENT_PLAYERS_HOUSE_MOM_2
	const_skip
	const_skip
	const_skip
	const_skip
	const EVENT_GOLDENROD_CITY_ROCKET_TAKEOVER
	const EVENT_RADIO_TOWER_ROCKET_TAKEOVER
	const EVENT_GOLDENROD_CITY_CIVILIANS
	const EVENT_RADIO_TOWER_CIVILIANS_AFTER
	const EVENT_RADIO_TOWER_BLACKBELT_BLOCKS_STAIRS
	const EVENT_OLIVINE_LIGHTHOUSE_JASMINE
	const EVENT_OLIVINE_GYM_JASMINE
	const EVENT_LAKE_OF_RAGE_LANCE
	const EVENT_MAHOGANY_MART_LANCE_AND_DRAGONITE
	const EVENT_TEAM_ROCKET_BASE_B2F_LANCE
	const EVENT_TEAM_ROCKET_BASE_B3F_LANCE_PASSWORDS
	const EVENT_DRAGONS_DEN_CLAIR
	const EVENT_TEAM_ROCKET_BASE_SECURITY_GRUNTS
	const EVENT_TEAM_ROCKET_BASE_POPULATION
	const EVENT_TEAM_ROCKET_BASE_B3F_EXECUTIVE
	const EVENT_ROUTE_15_GATE_ROCKETS
	const EVENT_TEAM_ROCKET_BASE_B2F_EXECUTIVE
	const EVENT_TEAM_ROCKET_BASE_B2F_GRUNT_WITH_EXECUTIVE
	const EVENT_TEAM_ROCKET_BASE_B2F_DRAGONITE
	const EVENT_TEAM_ROCKET_BASE_B2F_ELECTRODE_1
	const EVENT_TEAM_ROCKET_BASE_B2F_ELECTRODE_2
	const EVENT_TEAM_ROCKET_BASE_B2F_ELECTRODE_3
	const EVENT_BLACKTHORN_CITY_SUPER_NERD_BLOCKS_GYM
	const EVENT_BLACKTHORN_CITY_SUPER_NERD_DOES_NOT_BLOCK_GYM
	const EVENT_DAY_CARE_MAN_IN_DAY_CARE
	const EVENT_DAY_CARE_MAN_ON_ROUTE_6
	const EVENT_DAY_CARE_MON_1
	const EVENT_DAY_CARE_MON_2
	const EVENT_ILEX_FOREST_SCYTHER
	const EVENT_ROUTE_6_ILEX_FOREST_GATE_TEACHER_BEHIND_COUNTER
	const EVENT_ROUTE_6_ILEX_FOREST_GATE_LASS
	const EVENT_ROUTE_6_ILEX_FOREST_GATE_TEACHER_IN_WALKWAY
	const EVENT_ILEX_FOREST_LASS
	const EVENT_ROUTE_6_ILEX_FOREST_GATE_TANGELA_BEHIND_COUNTER
	const EVENT_ROUTE_6_ILEX_FOREST_GATE_TANGELA_IN_WALKWAY
	const EVENT_GOLDENROD_SALE_OFF
	const EVENT_GOLDENROD_SALE_ON
	const_skip
	const EVENT_ILEX_FOREST_APPRENTICE
	const EVENT_ILEX_FOREST_CHARCOAL_MASTER
	const EVENT_CHARCOAL_KILN_SCYTHER
	const EVENT_CHARCOAL_KILN_APPRENTICE
	const EVENT_CHARCOAL_KILN_BOSS
	const EVENT_ROUTE_8_SUDOWOODO
	const_skip
	const_skip
	const_skip
	const EVENT_SLOWPOKE_WELL_ROCKETS
	const_skip
	const EVENT_GUIDE_GENT_IN_HIS_HOUSE
	const EVENT_GUIDE_GENT_VISIBLE_IN_CHERRYGROVE
	const_skip
	const_skip
	const_skip
	const EVENT_RUINS_OF_ALPH_OUTSIDE_SCIENTIST
	const EVENT_RUINS_OF_ALPH_RESEARCH_CENTER_SCIENTIST
	const EVENT_RUINS_OF_ALPH_INNER_CHAMBER_TOURISTS
	const EVENT_BOULDER_IN_BLACKTHORN_GYM_1
	const EVENT_BOULDER_IN_BLACKTHORN_GYM_2
	const EVENT_BOULDER_IN_BLACKTHORN_GYM_3
	const EVENT_BOULDER_IN_ICE_PATH_1
	const EVENT_BOULDER_IN_ICE_PATH_2
	const EVENT_BOULDER_IN_ICE_PATH_3
	const EVENT_BOULDER_IN_ICE_PATH_4
	const EVENT_BOULDER_IN_ICE_PATH_1A
	const EVENT_BOULDER_IN_ICE_PATH_2A
	const EVENT_BOULDER_IN_ICE_PATH_3A
	const EVENT_BOULDER_IN_ICE_PATH_4A
	const EVENT_MYSTERY_GIFT_DELIVERY_GUY
	const_skip
	const_skip
	const_skip
	const_skip
	const EVENT_BUG_CATCHING_CONTESTANT_1A
	const EVENT_BUG_CATCHING_CONTESTANT_2A
	const EVENT_BUG_CATCHING_CONTESTANT_3A
	const EVENT_BUG_CATCHING_CONTESTANT_4A
	const EVENT_BUG_CATCHING_CONTESTANT_5A
	const EVENT_BUG_CATCHING_CONTESTANT_6A
	const EVENT_BUG_CATCHING_CONTESTANT_7A
	const EVENT_BUG_CATCHING_CONTESTANT_8A
	const EVENT_BUG_CATCHING_CONTESTANT_9A
	const EVENT_BUG_CATCHING_CONTESTANT_10A
	const EVENT_BUG_CATCHING_CONTESTANT_1B
	const EVENT_BUG_CATCHING_CONTESTANT_2B
	const EVENT_BUG_CATCHING_CONTESTANT_3B
	const EVENT_BUG_CATCHING_CONTESTANT_4B
	const EVENT_BUG_CATCHING_CONTESTANT_5B
	const EVENT_BUG_CATCHING_CONTESTANT_6B
	const EVENT_BUG_CATCHING_CONTESTANT_7B
	const EVENT_BUG_CATCHING_CONTESTANT_8B
	const EVENT_BUG_CATCHING_CONTESTANT_9B
	const EVENT_BUG_CATCHING_CONTESTANT_10B
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const EVENT_OLIVINE_PORT_PASSAGE_POKEFAN_M
	const EVENT_ROUTE_7_NATIONAL_PARK_GATE_YOUNGSTER
	const EVENT_LAKE_OF_RAGE_CIVILIANS
	const EVENT_MAHOGANY_MART_OWNERS
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const EVENT_TIN_TOWER_ROOF_HO_OH
	const EVENT_WHIRL_ISLAND_LUGIA_CHAMBER_LUGIA
	const EVENT_KURTS_HOUSE_KURT_1
	const EVENT_KURTS_HOUSE_KURT_2
	const_skip
	const EVENT_PLAYERS_HOUSE_2F_CONSOLE
	const EVENT_PLAYERS_HOUSE_2F_DOLL_1
	const EVENT_PLAYERS_HOUSE_2F_DOLL_2
	const EVENT_PLAYERS_HOUSE_2F_BIG_DOLL
	const EVENT_ROUTE_7_NATIONAL_PARK_GATE_OFFICER_CONTEST_DAY
	const EVENT_ROUTE_7_NATIONAL_PARK_GATE_OFFICER_NOT_CONTEST_DAY
	const EVENT_ROUTE_8_NATIONAL_PARK_GATE_OFFICER_CONTEST_DAY
	const EVENT_ROUTE_8_NATIONAL_PARK_GATE_OFFICER_NOT_CONTEST_DAY
	const EVENT_GOLDENROD_TRAIN_STATION_GENTLEMAN
	const EVENT_BURNED_TOWER_B1F_BEASTS_1
	const EVENT_BURNED_TOWER_B1F_BEASTS_2
	const EVENT_BLACKTHORN_CITY_GRAMPS_BLOCKS_DRAGONS_DEN
	const EVENT_BLACKTHORN_CITY_GRAMPS_NOT_BLOCKING_DRAGONS_DEN
	const EVENT_RUINS_OF_ALPH_LILEEP_CHAMBER_RECEPTIONIST
	const EVENT_OPENED_MT_SILVER
	const_skip
	const EVENT_LAKE_OF_RAGE_RED_GYARADOS
	const EVENT_GOLDENROD_UNDERGROUND_GRANNY
	const EVENT_GOLDENROD_UNDERGROUND_GRAMPS
	const EVENT_GOLDENROD_UNDERGROUND_OLDER_HAIRCUT_BROTHER
	const EVENT_GOLDENROD_UNDERGROUND_YOUNGER_HAIRCUT_BROTHER
	const_skip
	const_skip
	const EVENT_ROUTE_4_FRIEDA_OF_FRIDAY
	const EVENT_ROUTE_1_TUSCANY_OF_TUESDAY
	const EVENT_ROUTE_8_ARTHUR_OF_THURSDAY
	const EVENT_ROUTE_9_SUNNY_OF_SUNDAY
	const EVENT_LAKE_OF_RAGE_WESLEY_OF_WEDNESDAY
	const EVENT_BLACKTHORN_CITY_SANTOS_OF_SATURDAY
	const EVENT_ROUTE_12_MONICA_OF_MONDAY
	const EVENT_LANCES_ROOM_OAK_AND_MARY
	const EVENT_UNION_CAVE_B2F_LAPRAS
	const EVENT_TEAM_ROCKET_DISBANDED
	const EVENT_RED_IN_MT_SILVER
	const EVENT_GOLDENROD_DEPT_STORE_5F_HAPPINESS_EVENT_LADY
	const EVENT_BURNED_TOWER_MORTY
	const EVENT_BURNED_TOWER_1F_EUSINE
	const EVENT_RANG_CLEAR_BELL_1
	const EVENT_RANG_CLEAR_BELL_2
	const EVENT_FLORIA_AT_FLOWER_SHOP
	const EVENT_FLORIA_AT_SUDOWOODO
	const EVENT_MET_GOLDENROD_MOVE_TUTOR
	const_skip
; Unused: next 0 events
; (In pokegold the previous 4 event flags were not defined,
; but in pokecrystal the 'const_next 1900' is redundant.)

	const_next 1900
; Kanto people
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const EVENT_MT_MOON_SQUARE_ROCK
	const EVENT_MT_MOON_SQUARE_CLEFAIRY
	const_skip
	const EVENT_INDIGO_PLATEAU_POKECENTER_RIVAL
	const_skip
; Kanto itemballs
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
	const_skip
; New to Crystal
	const EVENT_KURTS_HOUSE_GRANDDAUGHTER_1
	const EVENT_KURTS_HOUSE_GRANDDAUGHTER_2
	const EVENT_RUINS_OF_ALPH_OUTSIDE_TOURIST_FISHER
	const EVENT_RUINS_OF_ALPH_OUTSIDE_TOURIST_YOUNGSTERS
	const EVENT_DRAGON_SHRINE_CLAIR
	const EVENT_BATTLE_TOWER_BATTLE_ROOM_YOUNGSTER
	const_skip
	const_skip
	const EVENT_HO_OH_ITEM_ROOM_SACRED_ASH
	const EVENT_HO_OH_ITEM_ROOM_CHOICE_BAND
	const EVENT_HO_OH_ITEM_ROOM_CHOICE_SPECS
	const EVENT_HO_OH_ITEM_ROOM_MUSCLE_BAND
	const EVENT_LILEEP_ITEM_ROOM_GRIP_CLAW
	const EVENT_LILEEP_ITEM_ROOM_FOCUS_SASH
	const EVENT_LILEEP_ITEM_ROOM_HEAVY_BOOTS
	const EVENT_LILEEP_ITEM_ROOM_ZOOM_LENS
	const EVENT_OMANYTE_ITEM_ROOM_LIFE_ORB
	const EVENT_OMANYTE_ITEM_ROOM_WEATHER_ROCK
	const EVENT_OMANYTE_ITEM_ROOM_BRIGHTPOWDER
	const EVENT_OMANYTE_ITEM_ROOM_FOCUS_BAND
	const EVENT_AERODACTYL_ITEM_ROOM_FLAME_ORB
	const EVENT_AERODACTYL_ITEM_ROOM_MOON_STONE
	const EVENT_AERODACTYL_ITEM_ROOM_METEOR_MITTS
	const EVENT_AERODACTYL_ITEM_ROOM_SUNSTONE
	const EVENT_AZALEA_TOWN_KURT
	const EVENT_ILEX_FOREST_KURT
	const EVENT_MOUNT_MORTAR_1F_INSIDE_MAX_POTION
	const EVENT_MOUNT_MORTAR_1F_INSIDE_NUGGET
	const EVENT_ECRUTEAK_GYM_GRAMPS
	const EVENT_ECRUTEAK_CITY_GRAMPS
	const EVENT_EUSINE_IN_BURNED_TOWER
	const EVENT_WISE_TRIOS_ROOM_WISE_TRIO_1
	const EVENT_WISE_TRIOS_ROOM_WISE_TRIO_2
	const EVENT_CIANWOOD_CITY_EUSINE
	const EVENT_SAW_SUICUNE_AT_CIANWOOD_CITY
	const EVENT_SAW_SUICUNE_ON_ROUTE_14
	const EVENT_SAW_SUICUNE_ON_ROUTE_8
	const EVENT_ECRUTEAK_TIN_TOWER_ENTRANCE_WANDERING_SAGE
	const EVENT_TIN_TOWER_1F_SUICUNE
	const EVENT_TIN_TOWER_1F_ENTEI
	const EVENT_TIN_TOWER_1F_RAIKOU
	const EVENT_TIN_TOWER_1F_EUSINE
	const EVENT_TIN_TOWER_1F_WISE_TRIO_1
	const_skip
	const EVENT_ROUTE_2_ANTIDOTE
	const_skip
	const EVENT_ILEX_FOREST_ANTIDOTE
	const EVENT_ILEX_FOREST_ETHER
	const EVENT_ROUTE_6_NUGGET
	const EVENT_ROUTE_16_MAX_REPEL
	const EVENT_ICE_PATH_1F_PROTEIN
	const EVENT_DRAGONS_DEN_B1F_CALCIUM
	const EVENT_DRAGONS_DEN_B1F_MAX_ELIXER
	const EVENT_SILVER_CAVE_ROOM_1_ULTRA_BALL
	const EVENT_SILVER_CAVE_ROOM_2_CALCIUM
	const EVENT_SILVER_CAVE_ROOM_2_ULTRA_BALL
	const EVENT_SILVER_CAVE_ROOM_2_PP_UP
	const EVENT_TIN_TOWER_1F_WISE_TRIO_2
	const EVENT_TIN_TOWER_6F_MAX_POTION
	const EVENT_TIN_TOWER_9F_HP_UP
	const EVENT_MOUNT_MORTAR_1F_INSIDE_IRON
	const EVENT_MOUNT_MORTAR_1F_INSIDE_ULTRA_BALL
	const EVENT_MOUNT_MORTAR_B1F_FULL_RESTORE
	const EVENT_MOUNT_MORTAR_B1F_MAX_ETHER
	const EVENT_MOUNT_MORTAR_B1F_PP_UP
	const EVENT_RADIO_TOWER_5F_ULTRA_BALL
	const EVENT_DARK_CAVE_VIOLET_ENTRANCE_RAIN_SHARD
	const EVENT_BATTLE_TOWER_OPEN_CIVILIANS
; Unused: next 48 events

	const_next 2048
DEF NUM_EVENTS EQU const_value ; 800
