AnimationPointers:
	table_width 2, AnimationPointers
	dw RotomAnimation
	dw VictiniAnimation
	dw DuraludonAnimation
	dw CharmanderAnimation
	dw CharmeleonAnimation
	dw CharizardAnimation
	dw SquirtleAnimation
	dw WartortleAnimation
	dw BlastoiseAnimation
	dw TorchicAnimation
	dw CombuskenAnimation
	dw BlazikenAnimation
	dw TurtwigAnimation
	dw GrotleAnimation
	dw TorterraAnimation
	dw PidgeyAnimation
	dw PidgeottoAnimation
	dw PidgeotAnimation
	dw BunearyAnimation
	dw LopunnyAnimation
	dw ShroomishAnimation
	dw BreloomAnimation
	dw SkorupiAnimation
	dw DrapionAnimation
	dw PikachuAnimation
	dw RaichuAnimation
	dw DrilburAnimation
	dw ExcadrillAnimation
	dw NidoranFAnimation
	dw NidorinaAnimation
	dw NidoqueenAnimation
	dw NidoranMAnimation
	dw NidorinoAnimation
	dw NidokingAnimation
	dw ClefairyAnimation
	dw ClefableAnimation
	dw MakuhitaAnimation
	dw HariyamaAnimation
	dw BaltoyAnimation
	dw ClaydolAnimation
	dw ZubatAnimation
	dw GolbatAnimation
	dw RhyhornAnimation
	dw OmanyteAnimation
	dw WyrdeerAnimation
	dw LarvestaAnimation
	dw LileepAnimation
	dw JoltikAnimation
	dw GalvantulaAnimation
	dw AxewAnimation
	dw FraxureAnimation
	dw MeowthAnimation
	dw PersianAnimation
	dw SwabluAnimation
	dw AltariaAnimation
	dw MankeyAnimation
	dw PrimeapeAnimation
	dw GrowlitheAnimation
	dw ArcanineAnimation
	dw GibleAnimation
	dw GabiteAnimation
	dw GarchompAnimation
	dw RowletAnimation
	dw DartrixAnimation
	dw DecidueyeAnimation
	dw VenipedeAnimation
	dw WhirlipedeAnimation
	dw ScolipedeAnimation
	dw BellsproutAnimation
	dw WeepinbellAnimation
	dw VictreebelAnimation
	dw TentacoolAnimation
	dw TentacruelAnimation
	dw SnoruntAnimation
	dw GlalieAnimation
	dw FroslassAnimation
	dw PonytaAnimation
	dw RapidashAnimation
	dw SlowpokeAnimation
	dw SlowbroAnimation
	dw MagnemiteAnimation
	dw MagnetonAnimation
	dw TropiusAnimation
	dw DoduoAnimation
	dw DodrioAnimation
	dw SeelAnimation
	dw DewgongAnimation
	dw GrimerAnimation
	dw MukAnimation
	dw RioluAnimation
	dw LucarioAnimation
	dw GastlyAnimation
	dw HaunterAnimation
	dw GengarAnimation
	dw OnixAnimation
	dw DrowzeeAnimation
	dw HypnoAnimation
	dw BronzorAnimation
	dw BronzongAnimation
	dw VoltorbAnimation
	dw ElectrodeAnimation
	dw WimpodAnimation
	dw GolisopodAnimation
	dw LitwickAnimation
	dw LampentAnimation
	dw RaltsAnimation
	dw KirliaAnimation
	dw YanmegaAnimation
	dw KoffingAnimation
	dw WeezingAnimation
	dw MagnezoneAnimation
	dw UrsalunaAnimation
	dw ChanseyAnimation
	dw TangelaAnimation
	dw GliscorAnimation
	dw HorseaAnimation
	dw SeadraAnimation
	dw VolcaronaAnimation
	dw SmoochumAnimation
	dw StaryuAnimation
	dw StarmieAnimation
	dw MismagiusAnimation
	dw ScytherAnimation
	dw JynxAnimation
	dw ElectabuzzAnimation
	dw KatuAnimation
	dw AnnihilapeAnimation
	dw TaurosAnimation
	dw MagikarpAnimation
	dw GyaradosAnimation
	dw LaprasAnimation
	dw DittoAnimation
	dw EeveeAnimation
	dw KleavorAnimation
	dw TangrowthAnimation
	dw MamoswineAnimation
	dw PorygonAnimation
	dw WeavileAnimation
	dw OmastarAnimation
	dw SneaslerAnimation
	dw DarkraiAnimation
	dw AerodactylAnimation
	dw SnorlaxAnimation
	dw ArticunoAnimation
	dw ZapdosAnimation
	dw MoltresAnimation
	dw BagonAnimation
	dw ShelgonAnimation
	dw SalamenceAnimation
	dw MewtwoAnimation
	dw MewAnimation
	dw ChikoritaAnimation
	dw BayleefAnimation
	dw MeganiumAnimation
	dw CyndaquilAnimation
	dw QuilavaAnimation
	dw TyphlosionAnimation
	dw TotodileAnimation
	dw CroconawAnimation
	dw FeraligatrAnimation
	dw WurmpleAnimation
	dw SilcoonAnimation
	dw HoothootAnimation
	dw NoctowlAnimation
	dw BeautiflyAnimation
	dw DustoxAnimation
	dw SpinarakAnimation
	dw AriadosAnimation
	dw CrobatAnimation
	dw ChinchouAnimation
	dw LanturnAnimation
	dw RegirockAnimation
	dw RegiceAnimation
	dw RegisteelAnimation
	dw TogepiAnimation
	dw TogeticAnimation
	dw NatuAnimation
	dw XatuAnimation
	dw MareepAnimation
	dw FlaaffyAnimation
	dw AmpharosAnimation
	dw CascoonAnimation
	dw MarillAnimation
	dw AzumarillAnimation
	dw SudowoodoAnimation
	dw CradilyAnimation
	dw SnoverAnimation
	dw AbomasnowAnimation
	dw SolrockAnimation
	dw LunatoneAnimation
	dw SunkernAnimation
	dw SunfloraAnimation
	dw YanmaAnimation
	dw WooperAnimation
	dw QuagsireAnimation
	dw PorygonZAnimation
	dw UmbreonAnimation
	dw RhydonAnimation
	dw TogekissAnimation
	dw MisdreavusAnimation
	dw UnownAnimation
	dw SylveonAnimation
	dw ChandelureAnimation
	dw FerrothornAnimation
	dw FerroseedAnimation
	dw HaxorusAnimation
	dw GligarAnimation
	dw SteelixAnimation
	dw SnubbullAnimation
	dw GranbullAnimation
	dw ElekidAnimation
	dw ScizorAnimation
	dw ShuckleAnimation
	dw HeracrossAnimation
	dw SneaselAnimation
	dw TeddiursaAnimation
	dw UrsaringAnimation
	dw FeebasAnimation
	dw MiloticAnimation
	dw SwinubAnimation
	dw PiloswineAnimation
	dw CorsolaAnimation
	dw RemoraidAnimation
	dw OctilleryAnimation
	dw DelibirdAnimation
	dw MantineAnimation
	dw SkarmoryAnimation
	dw HoundourAnimation
	dw HoundoomAnimation
	dw KingdraAnimation
	dw PhanpyAnimation
	dw DonphanAnimation
	dw Porygon2Animation
	dw StantlerAnimation
	dw SmeargleAnimation
	dw GalladeAnimation
	dw GardevoirAnimation
	dw AbsolAnimation
	dw RegigigasAnimation
	dw NownAnimation
	dw MiltankAnimation
	dw BlisseyAnimation
	dw RaikouAnimation
	dw EnteiAnimation
	dw SuicuneAnimation
	dw LarvitarAnimation
	dw PupitarAnimation
	dw TyranitarAnimation
	dw LugiaAnimation
	dw HoOhAnimation
	dw CelebiAnimation
	dw GholdengoAnimation
	assert_table_length NUM_POKEMON
