AnimationPointers:
	table_width 2, AnimationPointers
	dw CyndaquilAnimation
	dw QuilavaAnimation
	dw TyphlosionAnimation
	dw TotodileAnimation
	dw CroconawAnimation
	dw FeraligatrAnimation
	dw ChikoritaAnimation
	dw BayleefAnimation
	dw MeganiumAnimation
	dw TogepiAnimation
	dw TogeticAnimation
	dw TogekissAnimation
	dw CharmanderAnimation
	dw CharmeleonAnimation
	dw CharizardAnimation
	dw SquirtleAnimation
	dw WartortleAnimation
	dw BlastoiseAnimation
	dw TurtwigAnimation
	dw GrotleAnimation
	dw TorterraAnimation
	dw PikachuAnimation
	dw RaichuAnimation
	dw EeveeAnimation
	dw UmbreonAnimation
	dw SylveonAnimation
	dw TorchicAnimation
	dw CombuskenAnimation
	dw BlazikenAnimation
	dw FeebasAnimation
	dw MiloticAnimation
	dw RowletAnimation
	dw DartrixAnimation
	dw DecidueyeAnimation
	dw RaltsAnimation
	dw KirliaAnimation
	dw GardevoirAnimation
	dw GalladeAnimation
	dw WurmpleAnimation
	dw SilcoonAnimation
	dw BeautiflyAnimation
	dw CascoonAnimation
	dw DustoxAnimation
	dw YanmaAnimation
	dw YanmegaAnimation
	dw SunkernAnimation
	dw SunfloraAnimation
	dw BunearyAnimation
	dw LopunnyAnimation
	dw PidgeyAnimation
	dw PidgeottoAnimation
	dw PidgeotAnimation
	dw HoothootAnimation
	dw NoctowlAnimation
	dw ZubatAnimation
	dw GolbatAnimation
	dw CrobatAnimation
	dw TeddiursaAnimation
	dw UrsaringAnimation
	dw UrsalunaAnimation
	dw PhanpyAnimation
	dw DonphanAnimation
	dw BellsproutAnimation
	dw WeepinbellAnimation
	dw VictreebelAnimation
	dw MareepAnimation
	dw FlaaffyAnimation
	dw AmpharosAnimation
	dw NidoranFAnimation
	dw NidorinaAnimation
	dw NidoqueenAnimation
	dw NidoranMAnimation
	dw NidorinoAnimation
	dw NidokingAnimation
	dw WimpodAnimation
	dw GolisopodAnimation
	dw MarillAnimation
	dw AzumarillAnimation
	dw RhyhornAnimation
	dw RhydonAnimation
	dw DrilburAnimation
	dw ExcadrillAnimation
	dw OnixAnimation
	dw SteelixAnimation
	dw MagikarpAnimation
	dw GyaradosAnimation
	dw GastlyAnimation
	dw HaunterAnimation
	dw GengarAnimation
	dw SwabluAnimation
	dw AltariaAnimation
	dw NatuAnimation
	dw KatuAnimation
	dw XatuAnimation
	dw SmeargleAnimation
	dw GrowlitheAnimation
	dw ArcanineAnimation
	dw HoundourAnimation
	dw HoundoomAnimation
	dw WooperAnimation
	dw QuagsireAnimation
	dw GligarAnimation
	dw GliscorAnimation
	dw GibleAnimation
	dw GabiteAnimation
	dw GarchompAnimation
	dw MakuhitaAnimation
	dw HariyamaAnimation
	dw DoduoAnimation
	dw DodrioAnimation
	dw PonytaAnimation
	dw RapidashAnimation
	dw SlowpokeAnimation
	dw SlowbroAnimation
	dw ShroomishAnimation
	dw BreloomAnimation
	dw SpinarakAnimation
	dw AriadosAnimation
	dw VenipedeAnimation
	dw WhirlipedeAnimation
	dw ScolipedeAnimation
	dw JoltikAnimation
	dw GalvantulaAnimation
	dw SkorupiAnimation
	dw DrapionAnimation
	dw LarvestaAnimation
	dw VolcaronaAnimation
	dw TropiusAnimation
	dw MankeyAnimation
	dw PrimeapeAnimation
	dw AnnihilapeAnimation
	dw FerroseedAnimation
	dw FerrothornAnimation
	dw ScytherAnimation
	dw ScizorAnimation
	dw KleavorAnimation
	dw HeracrossAnimation
	dw TangelaAnimation
	dw TangrowthAnimation
	dw MeowthAnimation
	dw PersianAnimation
	dw SnubbullAnimation
	dw GranbullAnimation
	dw DrowzeeAnimation
	dw HypnoAnimation
	dw SudowoodoAnimation
	dw KoffingAnimation
	dw WeezingAnimation
	dw GrimerAnimation
	dw MukAnimation
	dw LitwickAnimation
	dw LampentAnimation
	dw ChandelureAnimation
	dw MiltankAnimation
	dw TaurosAnimation
	dw VoltorbAnimation
	dw ElectrodeAnimation
	dw ElekidAnimation
	dw ElectabuzzAnimation
	dw MagnemiteAnimation
	dw MagnetonAnimation
	dw MagnezoneAnimation
	dw ShuckleAnimation
	dw CorsolaAnimation
	dw StaryuAnimation
	dw StarmieAnimation
	dw RemoraidAnimation
	dw OctilleryAnimation
	dw ChinchouAnimation
	dw LanturnAnimation
	dw MantineAnimation
	dw TentacoolAnimation
	dw TentacruelAnimation
	dw SeelAnimation
	dw DewgongAnimation
	dw HorseaAnimation
	dw SeadraAnimation
	dw KingdraAnimation
	dw LaprasAnimation
	dw ClefairyAnimation
	dw ClefableAnimation
	dw SolrockAnimation
	dw LunatoneAnimation
	dw StantlerAnimation
	dw WyrdeerAnimation
	dw DelibirdAnimation
	dw SmoochumAnimation
	dw JynxAnimation
	dw SnoruntAnimation
	dw GlalieAnimation
	dw FroslassAnimation
	dw SwinubAnimation
	dw PiloswineAnimation
	dw MamoswineAnimation
	dw SneaselAnimation
	dw WeavileAnimation
	dw SneaslerAnimation
	dw SnoverAnimation
	dw AbomasnowAnimation
	dw BaltoyAnimation
	dw ClaydolAnimation
	dw RioluAnimation
	dw LucarioAnimation
	dw BronzorAnimation
	dw BronzongAnimation
	dw SkarmoryAnimation
	dw MisdreavusAnimation
	dw MismagiusAnimation
	dw ChanseyAnimation
	dw BlisseyAnimation
	dw SnorlaxAnimation
	dw LarvitarAnimation
	dw PupitarAnimation
	dw TyranitarAnimation
	dw BagonAnimation
	dw ShelgonAnimation
	dw SalamenceAnimation
	dw AxewAnimation
	dw FraxureAnimation
	dw HaxorusAnimation
	dw PorygonAnimation
	dw Porygon2Animation
	dw PorygonZAnimation
	dw OmanyteAnimation
	dw OmastarAnimation
	dw LileepAnimation
	dw CradilyAnimation
	dw AerodactylAnimation
	dw RotomAnimation
	dw AbsolAnimation
	dw DuraludonAnimation
	dw GholdengoAnimation
	dw DarkraiAnimation
	dw RegirockAnimation
	dw RegiceAnimation
	dw RegisteelAnimation
	dw RegigigasAnimation
	dw ArticunoAnimation
	dw ZapdosAnimation
	dw MoltresAnimation
	dw LugiaAnimation
	dw RaikouAnimation
	dw EnteiAnimation
	dw SuicuneAnimation
	dw HoOhAnimation
	dw UnownAnimation
	dw NownAnimation
	dw VictiniAnimation
	dw CelebiAnimation
	dw DittoAnimation
	dw MewAnimation
	dw MewtwoAnimation
	assert_table_length NUM_POKEMON
