BitmasksPointers:
	table_width 2, BitmasksPointers
	dw RotomBitmasks
	dw VictiniBitmasks
	dw DuraludonBitmasks
	dw CharmanderBitmasks
	dw CharmeleonBitmasks
	dw CharizardBitmasks
	dw SquirtleBitmasks
	dw WartortleBitmasks
	dw BlastoiseBitmasks
	dw TorchicBitmasks
	dw CombuskenBitmasks
	dw BlazikenBitmasks
	dw TurtwigBitmasks
	dw GrotleBitmasks
	dw TorterraBitmasks
	dw PidgeyBitmasks
	dw PidgeottoBitmasks
	dw PidgeotBitmasks
	dw BunearyBitmasks
	dw LopunnyBitmasks
	dw ShroomishBitmasks
	dw BreloomBitmasks
	dw SkorupiBitmasks
	dw DrapionBitmasks
	dw PikachuBitmasks
	dw RaichuBitmasks
	dw DrilburBitmasks
	dw ExcadrillBitmasks
	dw NidoranFBitmasks
	dw NidorinaBitmasks
	dw NidoqueenBitmasks
	dw NidoranMBitmasks
	dw NidorinoBitmasks
	dw NidokingBitmasks
	dw ClefairyBitmasks
	dw ClefableBitmasks
	dw MakuhitaBitmasks
	dw HariyamaBitmasks
	dw BaltoyBitmasks
	dw ClaydolBitmasks
	dw ZubatBitmasks
	dw GolbatBitmasks
	dw RhyhornBitmasks
	dw OmanyteBitmasks
	dw WyrdeerBitmasks
	dw LarvestaBitmasks
	dw LileepBitmasks
	dw JoltikBitmasks
	dw GalvantulaBitmasks
	dw AxewBitmasks
	dw FraxureBitmasks
	dw MeowthBitmasks
	dw PersianBitmasks
	dw SwabluBitmasks
	dw AltariaBitmasks
	dw MankeyBitmasks
	dw PrimeapeBitmasks
	dw GrowlitheBitmasks
	dw ArcanineBitmasks
	dw GibleBitmasks
	dw GabiteBitmasks
	dw GarchompBitmasks
	dw RowletBitmasks
	dw DartrixBitmasks
	dw DecidueyeBitmasks
	dw VenipedeBitmasks
	dw WhirlipedeBitmasks
	dw ScolipedeBitmasks
	dw BellsproutBitmasks
	dw WeepinbellBitmasks
	dw VictreebelBitmasks
	dw TentacoolBitmasks
	dw TentacruelBitmasks
	dw SnoruntBitmasks
	dw GlalieBitmasks
	dw FroslassBitmasks
	dw PonytaBitmasks
	dw RapidashBitmasks
	dw SlowpokeBitmasks
	dw SlowbroBitmasks
	dw MagnemiteBitmasks
	dw MagnetonBitmasks
	dw TropiusBitmasks
	dw DoduoBitmasks
	dw DodrioBitmasks
	dw SeelBitmasks
	dw DewgongBitmasks
	dw GrimerBitmasks
	dw MukBitmasks
	dw RioluBitmasks
	dw LucarioBitmasks
	dw GastlyBitmasks
	dw HaunterBitmasks
	dw GengarBitmasks
	dw OnixBitmasks
	dw DrowzeeBitmasks
	dw HypnoBitmasks
	dw BronzorBitmasks
	dw BronzongBitmasks
	dw VoltorbBitmasks
	dw ElectrodeBitmasks
	dw WimpodBitmasks
	dw GolisopodBitmasks
	dw LitwickBitmasks
	dw LampentBitmasks
	dw RaltsBitmasks
	dw KirliaBitmasks
	dw YanmegaBitmasks
	dw KoffingBitmasks
	dw WeezingBitmasks
	dw MagnezoneBitmasks
	dw UrsalunaBitmasks
	dw ChanseyBitmasks
	dw TangelaBitmasks
	dw GliscorBitmasks
	dw HorseaBitmasks
	dw SeadraBitmasks
	dw VolcaronaBitmasks
	dw SmoochumBitmasks
	dw StaryuBitmasks
	dw StarmieBitmasks
	dw MismagiusBitmasks
	dw ScytherBitmasks
	dw JynxBitmasks
	dw ElectabuzzBitmasks
	dw KatuBitmasks
	dw AnnihilapeBitmasks
	dw TaurosBitmasks
	dw MagikarpBitmasks
	dw GyaradosBitmasks
	dw LaprasBitmasks
	dw DittoBitmasks
	dw EeveeBitmasks
	dw KleavorBitmasks
	dw TangrowthBitmasks
	dw MamoswineBitmasks
	dw PorygonBitmasks
	dw WeavileBitmasks
	dw OmastarBitmasks
	dw SneaslerBitmasks
	dw DarkraiBitmasks
	dw AerodactylBitmasks
	dw SnorlaxBitmasks
	dw ArticunoBitmasks
	dw ZapdosBitmasks
	dw MoltresBitmasks
	dw BagonBitmasks
	dw ShelgonBitmasks
	dw SalamenceBitmasks
	dw MewtwoBitmasks
	dw MewBitmasks
	dw ChikoritaBitmasks
	dw BayleefBitmasks
	dw MeganiumBitmasks
	dw CyndaquilBitmasks
	dw QuilavaBitmasks
	dw TyphlosionBitmasks
	dw TotodileBitmasks
	dw CroconawBitmasks
	dw FeraligatrBitmasks
	dw WurmpleBitmasks
	dw SilcoonBitmasks
	dw HoothootBitmasks
	dw NoctowlBitmasks
	dw BeautiflyBitmasks
	dw DustoxBitmasks
	dw SpinarakBitmasks
	dw AriadosBitmasks
	dw CrobatBitmasks
	dw ChinchouBitmasks
	dw LanturnBitmasks
	dw RegirockBitmasks
	dw RegiceBitmasks
	dw RegisteelBitmasks
	dw TogepiBitmasks
	dw TogeticBitmasks
	dw NatuBitmasks
	dw XatuBitmasks
	dw MareepBitmasks
	dw FlaaffyBitmasks
	dw AmpharosBitmasks
	dw CascoonBitmasks
	dw MarillBitmasks
	dw AzumarillBitmasks
	dw SudowoodoBitmasks
	dw CradilyBitmasks
	dw SnoverBitmasks
	dw AbomasnowBitmasks
	dw SolrockBitmasks
	dw LunatoneBitmasks
	dw SunkernBitmasks
	dw SunfloraBitmasks
	dw YanmaBitmasks
	dw WooperBitmasks
	dw QuagsireBitmasks
	dw PorygonZBitmasks
	dw UmbreonBitmasks
	dw RhydonBitmasks
	dw TogekissBitmasks
	dw MisdreavusBitmasks
	dw UnownBitmasks
	dw SylveonBitmasks
	dw ChandelureBitmasks
	dw FerrothornBitmasks
	dw FerroseedBitmasks
	dw HaxorusBitmasks
	dw GligarBitmasks
	dw SteelixBitmasks
	dw SnubbullBitmasks
	dw GranbullBitmasks
	dw ElekidBitmasks
	dw ScizorBitmasks
	dw ShuckleBitmasks
	dw HeracrossBitmasks
	dw SneaselBitmasks
	dw TeddiursaBitmasks
	dw UrsaringBitmasks
	dw FeebasBitmasks
	dw MiloticBitmasks
	dw SwinubBitmasks
	dw PiloswineBitmasks
	dw CorsolaBitmasks
	dw RemoraidBitmasks
	dw OctilleryBitmasks
	dw DelibirdBitmasks
	dw MantineBitmasks
	dw SkarmoryBitmasks
	dw HoundourBitmasks
	dw HoundoomBitmasks
	dw KingdraBitmasks
	dw PhanpyBitmasks
	dw DonphanBitmasks
	dw Porygon2Bitmasks
	dw StantlerBitmasks
	dw SmeargleBitmasks
	dw GalladeBitmasks
	dw GardevoirBitmasks
	dw AbsolBitmasks
	dw RegigigasBitmasks
	dw NownBitmasks
	dw MiltankBitmasks
	dw BlisseyBitmasks
	dw RaikouBitmasks
	dw EnteiBitmasks
	dw SuicuneBitmasks
	dw LarvitarBitmasks
	dw PupitarBitmasks
	dw TyranitarBitmasks
	dw LugiaBitmasks
	dw HoOhBitmasks
	dw CelebiBitmasks
	dw GholdengoBitmasks
	assert_table_length NUM_POKEMON
