FramesPointers:
	table_width 2, FramesPointers
	dw CyndaquilFrames
	dw QuilavaFrames
	dw TyphlosionFrames
	dw TotodileFrames
	dw CroconawFrames
	dw FeraligatrFrames
	dw ChikoritaFrames
	dw BayleefFrames
	dw MeganiumFrames
	dw TogepiFrames
	dw TogeticFrames
	dw TogekissFrames
	dw CharmanderFrames
	dw CharmeleonFrames
	dw CharizardFrames
	dw SquirtleFrames
	dw WartortleFrames
	dw BlastoiseFrames
	dw TurtwigFrames
	dw GrotleFrames
	dw TorterraFrames
	dw PikachuFrames
	dw RaichuFrames
	dw EeveeFrames
	dw UmbreonFrames
	dw SylveonFrames
	dw TorchicFrames
	dw CombuskenFrames
	dw BlazikenFrames
	dw FeebasFrames
	dw MiloticFrames
	dw RowletFrames
	dw DartrixFrames
	dw DecidueyeFrames
	dw RaltsFrames
	dw KirliaFrames
	dw GardevoirFrames
	dw GalladeFrames
	dw WurmpleFrames
	dw SilcoonFrames
	dw BeautiflyFrames
	dw CascoonFrames
	dw DustoxFrames
	dw YanmaFrames
	dw YanmegaFrames
	dw SunkernFrames
	dw SunfloraFrames
	dw BunearyFrames
	dw LopunnyFrames
	dw PidgeyFrames
	dw PidgeottoFrames
	dw PidgeotFrames
	dw HoothootFrames
	dw NoctowlFrames
	dw ZubatFrames
	dw GolbatFrames
	dw CrobatFrames
	dw TeddiursaFrames
	dw UrsaringFrames
	dw UrsalunaFrames
	dw PhanpyFrames
	dw DonphanFrames
	dw BellsproutFrames
	dw WeepinbellFrames
	dw VictreebelFrames
	dw MareepFrames
	dw FlaaffyFrames
	dw AmpharosFrames
	dw NidoranFFrames
	dw NidorinaFrames
	dw NidoqueenFrames
	dw NidoranMFrames
	dw NidorinoFrames
	dw NidokingFrames
	dw WimpodFrames
	dw GolisopodFrames
	dw MarillFrames
	dw AzumarillFrames
	dw RhyhornFrames
	dw RhydonFrames
	dw DrilburFrames
	dw ExcadrillFrames
	dw OnixFrames
	dw SteelixFrames
	dw MagikarpFrames
	dw GyaradosFrames
	dw GastlyFrames
	dw HaunterFrames
	dw GengarFrames
	dw SwabluFrames
	dw AltariaFrames
	dw NatuFrames
	dw KatuFrames
	dw XatuFrames
	dw SmeargleFrames
	dw GrowlitheFrames
	dw ArcanineFrames
	dw HoundourFrames
	dw HoundoomFrames
	dw WooperFrames
	dw QuagsireFrames
	dw GligarFrames
	dw GliscorFrames
	dw GibleFrames
	dw GabiteFrames
	dw GarchompFrames
	dw MakuhitaFrames
	dw HariyamaFrames
	dw DoduoFrames
	dw DodrioFrames
	dw PonytaFrames
	dw RapidashFrames
	dw SlowpokeFrames
	dw SlowbroFrames
	dw ShroomishFrames
	dw BreloomFrames
	dw SpinarakFrames
	dw AriadosFrames
	dw VenipedeFrames
	dw WhirlipedeFrames
	dw ScolipedeFrames
	dw JoltikFrames
	dw GalvantulaFrames
	dw SkorupiFrames
	dw DrapionFrames
	dw LarvestaFrames
	dw VolcaronaFrames
	dw TropiusFrames
	dw MankeyFrames
	dw PrimeapeFrames
	dw AnnihilapeFrames
	dw FerroseedFrames
	dw FerrothornFrames
	dw ScytherFrames
	dw ScizorFrames
	dw KleavorFrames
	dw HeracrossFrames
	dw TangelaFrames
	dw TangrowthFrames
	dw MeowthFrames
	dw PersianFrames
	dw SnubbullFrames
	dw GranbullFrames
	dw DrowzeeFrames
	dw HypnoFrames
	dw SudowoodoFrames
	dw KoffingFrames
	dw WeezingFrames
	dw GrimerFrames
	dw MukFrames
	dw LitwickFrames
	dw LampentFrames
	dw ChandelureFrames
	dw MiltankFrames
	dw TaurosFrames
	dw VoltorbFrames
	dw ElectrodeFrames
	dw ElekidFrames
	dw ElectabuzzFrames
	dw MagnemiteFrames
	dw MagnetonFrames
	dw MagnezoneFrames
	dw ShuckleFrames
	dw CorsolaFrames
	dw StaryuFrames
	dw StarmieFrames
	dw RemoraidFrames
	dw OctilleryFrames
	dw ChinchouFrames
	dw LanturnFrames
	dw MantineFrames
	dw TentacoolFrames
	dw TentacruelFrames
	dw SeelFrames
	dw DewgongFrames
	dw HorseaFrames
	dw SeadraFrames
	dw KingdraFrames
	dw LaprasFrames
	dw ClefairyFrames
	dw ClefableFrames
	dw SolrockFrames
	dw LunatoneFrames
	dw StantlerFrames
	dw WyrdeerFrames
	dw DelibirdFrames
	dw SmoochumFrames
	dw JynxFrames
	dw SnoruntFrames
	dw GlalieFrames
	dw FroslassFrames
	dw SwinubFrames
	dw PiloswineFrames
	dw MamoswineFrames
	dw SneaselFrames
	dw WeavileFrames
	dw SneaslerFrames
	dw SnoverFrames
	dw AbomasnowFrames
	dw BaltoyFrames
	dw ClaydolFrames
	dw RioluFrames
	dw LucarioFrames
	dw BronzorFrames
	dw BronzongFrames
	dw SkarmoryFrames
	dw MisdreavusFrames
	dw MismagiusFrames
	dw ChanseyFrames
	dw BlisseyFrames
	dw SnorlaxFrames
	dw LarvitarFrames
	dw PupitarFrames
	dw TyranitarFrames
	dw BagonFrames
	dw ShelgonFrames
	dw SalamenceFrames
	dw AxewFrames
	dw FraxureFrames
	dw HaxorusFrames
	dw PorygonFrames
	dw Porygon2Frames
	dw PorygonZFrames
	dw OmanyteFrames
	dw OmastarFrames
	dw LileepFrames
	dw CradilyFrames
	dw AerodactylFrames
	dw RotomFrames
	dw AbsolFrames
	dw DuraludonFrames
	dw GholdengoFrames
	dw DarkraiFrames
	dw RegirockFrames
	dw RegiceFrames
	dw RegisteelFrames
	dw RegigigasFrames
	dw ArticunoFrames
	dw ZapdosFrames
	dw MoltresFrames
	dw LugiaFrames
	dw RaikouFrames
	dw EnteiFrames
	dw SuicuneFrames
	dw HoOhFrames
	dw UnownFrames
	dw NownFrames
	dw VictiniFrames
	dw CelebiFrames
	dw DittoFrames
	dw MewFrames
	dw MewtwoFrames
	assert_table_length NUM_POKEMON
