AnimationIdlePointers:
	table_width 2, AnimationIdlePointers
	dw RotomAnimationIdle
	dw VictiniAnimationIdle
	dw DuraludonAnimationIdle
	dw CharmanderAnimationIdle
	dw CharmeleonAnimationIdle
	dw CharizardAnimationIdle
	dw SquirtleAnimationIdle
	dw WartortleAnimationIdle
	dw BlastoiseAnimationIdle
	dw TorchicAnimationIdle
	dw CombuskenAnimationIdle
	dw BlazikenAnimationIdle
	dw TurtwigAnimationIdle
	dw GrotleAnimationIdle
	dw TorterraAnimationIdle
	dw PidgeyAnimationIdle
	dw PidgeottoAnimationIdle
	dw PidgeotAnimationIdle
	dw BunearyAnimationIdle
	dw LopunnyAnimationIdle
	dw ShroomishAnimationIdle
	dw BreloomAnimationIdle
	dw SkorupiAnimationIdle
	dw DrapionAnimationIdle
	dw PikachuAnimationIdle
	dw RaichuAnimationIdle
	dw DrilburAnimationIdle
	dw ExcadrillAnimationIdle
	dw NidoranFAnimationIdle
	dw NidorinaAnimationIdle
	dw NidoqueenAnimationIdle
	dw NidoranMAnimationIdle
	dw NidorinoAnimationIdle
	dw NidokingAnimationIdle
	dw ClefairyAnimationIdle
	dw ClefableAnimationIdle
	dw MakuhitaAnimationIdle
	dw HariyamaAnimationIdle
	dw BaltoyAnimationIdle
	dw ClaydolAnimationIdle
	dw ZubatAnimationIdle
	dw GolbatAnimationIdle
	dw RhyhornAnimationIdle
	dw OmanyteAnimationIdle
	dw WyrdeerAnimationIdle
	dw LarvestaAnimationIdle
	dw LileepAnimationIdle
	dw JoltikAnimationIdle
	dw GalvantulaAnimationIdle
	dw AxewAnimationIdle
	dw FraxureAnimationIdle
	dw MeowthAnimationIdle
	dw PersianAnimationIdle
	dw SwabluAnimationIdle
	dw AltariaAnimationIdle
	dw MankeyAnimationIdle
	dw PrimeapeAnimationIdle
	dw GrowlitheAnimationIdle
	dw ArcanineAnimationIdle
	dw GibleAnimationIdle
	dw GabiteAnimationIdle
	dw GarchompAnimationIdle
	dw RowletAnimationIdle
	dw DartrixAnimationIdle
	dw DecidueyeAnimationIdle
	dw VenipedeAnimationIdle
	dw WhirlipedeAnimationIdle
	dw ScolipedeAnimationIdle
	dw BellsproutAnimationIdle
	dw WeepinbellAnimationIdle
	dw VictreebelAnimationIdle
	dw TentacoolAnimationIdle
	dw TentacruelAnimationIdle
	dw SnoruntAnimationIdle
	dw GlalieAnimationIdle
	dw FroslassAnimationIdle
	dw PonytaAnimationIdle
	dw RapidashAnimationIdle
	dw SlowpokeAnimationIdle
	dw SlowbroAnimationIdle
	dw MagnemiteAnimationIdle
	dw MagnetonAnimationIdle
	dw TropiusAnimationIdle
	dw DoduoAnimationIdle
	dw DodrioAnimationIdle
	dw SeelAnimationIdle
	dw DewgongAnimationIdle
	dw GrimerAnimationIdle
	dw MukAnimationIdle
	dw RioluAnimationIdle
	dw LucarioAnimationIdle
	dw GastlyAnimationIdle
	dw HaunterAnimationIdle
	dw GengarAnimationIdle
	dw OnixAnimationIdle
	dw DrowzeeAnimationIdle
	dw HypnoAnimationIdle
	dw BronzorAnimationIdle
	dw BronzongAnimationIdle
	dw VoltorbAnimationIdle
	dw ElectrodeAnimationIdle
	dw WimpodAnimationIdle
	dw GolisopodAnimationIdle
	dw LitwickAnimationIdle
	dw LampentAnimationIdle
	dw RaltsAnimationIdle
	dw KirliaAnimationIdle
	dw YanmegaAnimationIdle
	dw KoffingAnimationIdle
	dw WeezingAnimationIdle
	dw MagnezoneAnimationIdle
	dw UrsalunaAnimationIdle
	dw ChanseyAnimationIdle
	dw TangelaAnimationIdle
	dw GliscorAnimationIdle
	dw HorseaAnimationIdle
	dw SeadraAnimationIdle
	dw VolcaronaAnimationIdle
	dw SmoochumAnimationIdle
	dw StaryuAnimationIdle
	dw StarmieAnimationIdle
	dw MismagiusAnimationIdle
	dw ScytherAnimationIdle
	dw JynxAnimationIdle
	dw ElectabuzzAnimationIdle
	dw KatuAnimationIdle
	dw AnnihilapeAnimationIdle
	dw TaurosAnimationIdle
	dw MagikarpAnimationIdle
	dw GyaradosAnimationIdle
	dw LaprasAnimationIdle
	dw DittoAnimationIdle
	dw EeveeAnimationIdle
	dw KleavorAnimationIdle
	dw TangrowthAnimationIdle
	dw MamoswineAnimationIdle
	dw PorygonAnimationIdle
	dw WeavileAnimationIdle
	dw OmastarAnimationIdle
	dw SneaslerAnimationIdle
	dw DarkraiAnimationIdle
	dw AerodactylAnimationIdle
	dw SnorlaxAnimationIdle
	dw ArticunoAnimationIdle
	dw ZapdosAnimationIdle
	dw MoltresAnimationIdle
	dw BagonAnimationIdle
	dw ShelgonAnimationIdle
	dw SalamenceAnimationIdle
	dw MewtwoAnimationIdle
	dw MewAnimationIdle
	dw ChikoritaAnimationIdle
	dw BayleefAnimationIdle
	dw MeganiumAnimationIdle
	dw CyndaquilAnimationIdle
	dw QuilavaAnimationIdle
	dw TyphlosionAnimationIdle
	dw TotodileAnimationIdle
	dw CroconawAnimationIdle
	dw FeraligatrAnimationIdle
	dw WurmpleAnimationIdle
	dw SilcoonAnimationIdle
	dw HoothootAnimationIdle
	dw NoctowlAnimationIdle
	dw BeautiflyAnimationIdle
	dw DustoxAnimationIdle
	dw SpinarakAnimationIdle
	dw AriadosAnimationIdle
	dw CrobatAnimationIdle
	dw ChinchouAnimationIdle
	dw LanturnAnimationIdle
	dw RegirockAnimationIdle
	dw RegiceAnimationIdle
	dw RegisteelAnimationIdle
	dw TogepiAnimationIdle
	dw TogeticAnimationIdle
	dw NatuAnimationIdle
	dw XatuAnimationIdle
	dw MareepAnimationIdle
	dw FlaaffyAnimationIdle
	dw AmpharosAnimationIdle
	dw CascoonAnimationIdle
	dw MarillAnimationIdle
	dw AzumarillAnimationIdle
	dw SudowoodoAnimationIdle
	dw CradilyAnimationIdle
	dw SnoverAnimationIdle
	dw AbomasnowAnimationIdle
	dw SolrockAnimationIdle
	dw LunatoneAnimationIdle
	dw SunkernAnimationIdle
	dw SunfloraAnimationIdle
	dw YanmaAnimationIdle
	dw WooperAnimationIdle
	dw QuagsireAnimationIdle
	dw PorygonZAnimationIdle
	dw UmbreonAnimationIdle
	dw RhydonAnimationIdle
	dw TogekissAnimationIdle
	dw MisdreavusAnimationIdle
	dw UnownAnimationIdle
	dw SylveonAnimationIdle
	dw ChandelureAnimationIdle
	dw FerrothornAnimationIdle
	dw FerroseedAnimationIdle
	dw HaxorusAnimationIdle
	dw GligarAnimationIdle
	dw SteelixAnimationIdle
	dw SnubbullAnimationIdle
	dw GranbullAnimationIdle
	dw ElekidAnimationIdle
	dw ScizorAnimationIdle
	dw ShuckleAnimationIdle
	dw HeracrossAnimationIdle
	dw SneaselAnimationIdle
	dw TeddiursaAnimationIdle
	dw UrsaringAnimationIdle
	dw FeebasAnimationIdle
	dw MiloticAnimationIdle
	dw SwinubAnimationIdle
	dw PiloswineAnimationIdle
	dw CorsolaAnimationIdle
	dw RemoraidAnimationIdle
	dw OctilleryAnimationIdle
	dw DelibirdAnimationIdle
	dw MantineAnimationIdle
	dw SkarmoryAnimationIdle
	dw HoundourAnimationIdle
	dw HoundoomAnimationIdle
	dw KingdraAnimationIdle
	dw PhanpyAnimationIdle
	dw DonphanAnimationIdle
	dw Porygon2AnimationIdle
	dw StantlerAnimationIdle
	dw SmeargleAnimationIdle
	dw GalladeAnimationIdle
	dw GardevoirAnimationIdle
	dw AbsolAnimationIdle
	dw RegigigasAnimationIdle
	dw NownAnimationIdle
	dw MiltankAnimationIdle
	dw BlisseyAnimationIdle
	dw RaikouAnimationIdle
	dw EnteiAnimationIdle
	dw SuicuneAnimationIdle
	dw LarvitarAnimationIdle
	dw PupitarAnimationIdle
	dw TyranitarAnimationIdle
	dw LugiaAnimationIdle
	dw HoOhAnimationIdle
	dw CelebiAnimationIdle
	dw GholdengoAnimationIdle
	assert_table_length NUM_POKEMON
